// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artists.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addArtistArtwork = `-- name: AddArtistArtwork :exec
INSERT INTO "ArtistArtwork" ("id", "artistId", "imageUrl", "position")
VALUES ($1, $2, $3, $4)
`

type AddArtistArtworkParams struct {
	ID       string `json:"id"`
	ArtistId string `json:"artistId"`
	ImageUrl string `json:"imageUrl"`
	Position int32  `json:"position"`
}

func (q *Queries) AddArtistArtwork(ctx context.Context, arg AddArtistArtworkParams) error {
	_, err := q.db.Exec(ctx, addArtistArtwork,
		arg.ID,
		arg.ArtistId,
		arg.ImageUrl,
		arg.Position,
	)
	return err
}

const clearArtistArtworks = `-- name: ClearArtistArtworks :exec
DELETE FROM "ArtistArtwork" WHERE "artistId" = $1
`

func (q *Queries) ClearArtistArtworks(ctx context.Context, artistid string) error {
	_, err := q.db.Exec(ctx, clearArtistArtworks, artistid)
	return err
}

const createArtist = `-- name: CreateArtist :one
INSERT INTO "Artist" ("id", "slug", "city", "country", "featuredImageUrl", "avatarUrl", "status", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id, slug, city, country, status, "wpId", "createdAt", "updatedAt", "avatarUrl", "featuredImageUrl", "instagramUrl"
`

type CreateArtistParams struct {
	ID               string        `json:"id"`
	Slug             string        `json:"slug"`
	City             *string       `json:"city"`
	Country          *string       `json:"country"`
	FeaturedImageUrl *string       `json:"featuredImageUrl"`
	AvatarUrl        *string       `json:"avatarUrl"`
	Status           ProductStatus `json:"status"`
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist,
		arg.ID,
		arg.Slug,
		arg.City,
		arg.Country,
		arg.FeaturedImageUrl,
		arg.AvatarUrl,
		arg.Status,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.City,
		&i.Country,
		&i.Status,
		&i.WpId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.FeaturedImageUrl,
		&i.InstagramUrl,
	)
	return i, err
}

const deleteArtist = `-- name: DeleteArtist :exec
DELETE FROM "Artist" WHERE "id" = $1
`

func (q *Queries) DeleteArtist(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteArtist, id)
	return err
}

const getArtistArtworks = `-- name: GetArtistArtworks :many
SELECT id, "artistId", position, "imageUrl" FROM "ArtistArtwork" WHERE "artistId" = $1 ORDER BY "position" ASC
`

func (q *Queries) GetArtistArtworks(ctx context.Context, artistid string) ([]ArtistArtwork, error) {
	rows, err := q.db.Query(ctx, getArtistArtworks, artistid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtistArtwork{}
	for rows.Next() {
		var i ArtistArtwork
		if err := rows.Scan(
			&i.ID,
			&i.ArtistId,
			&i.Position,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistByID = `-- name: GetArtistByID :one
SELECT id, slug, city, country, status, "wpId", "createdAt", "updatedAt", "avatarUrl", "featuredImageUrl", "instagramUrl" FROM "Artist" WHERE "id" = $1
`

func (q *Queries) GetArtistByID(ctx context.Context, id string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByID, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.City,
		&i.Country,
		&i.Status,
		&i.WpId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.FeaturedImageUrl,
		&i.InstagramUrl,
	)
	return i, err
}

const getArtistBySlug = `-- name: GetArtistBySlug :one
SELECT id, slug, city, country, status, "wpId", "createdAt", "updatedAt", "avatarUrl", "featuredImageUrl", "instagramUrl" FROM "Artist" WHERE "slug" = $1
`

func (q *Queries) GetArtistBySlug(ctx context.Context, slug string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistBySlug, slug)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.City,
		&i.Country,
		&i.Status,
		&i.WpId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.FeaturedImageUrl,
		&i.InstagramUrl,
	)
	return i, err
}

const getArtistTranslations = `-- name: GetArtistTranslations :many
SELECT id, "artistId", locale, name, bio FROM "ArtistTranslation" WHERE "artistId" = $1
`

func (q *Queries) GetArtistTranslations(ctx context.Context, artistid string) ([]ArtistTranslation, error) {
	rows, err := q.db.Query(ctx, getArtistTranslations, artistid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtistTranslation{}
	for rows.Next() {
		var i ArtistTranslation
		if err := rows.Scan(
			&i.ID,
			&i.ArtistId,
			&i.Locale,
			&i.Name,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtists = `-- name: ListArtists :many
SELECT a.id, a.slug, a.city, a.country, a.status, a."wpId", a."createdAt", a."updatedAt", a."avatarUrl", a."featuredImageUrl", a."instagramUrl", COUNT(*) OVER() AS total_count
FROM "Artist" a
WHERE a."status" = 'PUBLISHED'::"ProductStatus"
ORDER BY a."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListArtistsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListArtistsRow struct {
	ID               string           `json:"id"`
	Slug             string           `json:"slug"`
	City             *string          `json:"city"`
	Country          *string          `json:"country"`
	Status           ProductStatus    `json:"status"`
	WpId             *int32           `json:"wpId"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	UpdatedAt        pgtype.Timestamp `json:"updatedAt"`
	AvatarUrl        *string          `json:"avatarUrl"`
	FeaturedImageUrl *string          `json:"featuredImageUrl"`
	InstagramUrl     *string          `json:"instagramUrl"`
	TotalCount       int64            `json:"total_count"`
}

func (q *Queries) ListArtists(ctx context.Context, arg ListArtistsParams) ([]ListArtistsRow, error) {
	rows, err := q.db.Query(ctx, listArtists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtistsRow{}
	for rows.Next() {
		var i ListArtistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.City,
			&i.Country,
			&i.Status,
			&i.WpId,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvatarUrl,
			&i.FeaturedImageUrl,
			&i.InstagramUrl,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtist = `-- name: UpdateArtist :one
UPDATE "Artist"
SET "city" = COALESCE($2, "city"),
    "country" = COALESCE($3, "country"),
    "featuredImageUrl" = COALESCE($4, "featuredImageUrl"),
    "avatarUrl" = COALESCE($5, "avatarUrl"),
    "status" = COALESCE($6::"ProductStatus", "status"),
    "updatedAt" = NOW()
WHERE "id" = $1
RETURNING id, slug, city, country, status, "wpId", "createdAt", "updatedAt", "avatarUrl", "featuredImageUrl", "instagramUrl"
`

type UpdateArtistParams struct {
	ID               string            `json:"id"`
	City             *string           `json:"city"`
	Country          *string           `json:"country"`
	FeaturedImageUrl *string           `json:"featured_image_url"`
	AvatarUrl        *string           `json:"avatar_url"`
	Status           NullProductStatus `json:"status"`
}

func (q *Queries) UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, updateArtist,
		arg.ID,
		arg.City,
		arg.Country,
		arg.FeaturedImageUrl,
		arg.AvatarUrl,
		arg.Status,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.City,
		&i.Country,
		&i.Status,
		&i.WpId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.FeaturedImageUrl,
		&i.InstagramUrl,
	)
	return i, err
}

const upsertArtistTranslation = `-- name: UpsertArtistTranslation :one
INSERT INTO "ArtistTranslation" ("id", "artistId", "locale", "name", "bio")
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ("artistId", "locale") DO UPDATE
  SET "name" = EXCLUDED."name", "bio" = EXCLUDED."bio"
RETURNING id, "artistId", locale, name, bio
`

type UpsertArtistTranslationParams struct {
	ID       string  `json:"id"`
	ArtistId string  `json:"artistId"`
	Locale   Locale  `json:"locale"`
	Name     string  `json:"name"`
	Bio      *string `json:"bio"`
}

func (q *Queries) UpsertArtistTranslation(ctx context.Context, arg UpsertArtistTranslationParams) (ArtistTranslation, error) {
	row := q.db.QueryRow(ctx, upsertArtistTranslation,
		arg.ID,
		arg.ArtistId,
		arg.Locale,
		arg.Name,
		arg.Bio,
	)
	var i ArtistTranslation
	err := row.Scan(
		&i.ID,
		&i.ArtistId,
		&i.Locale,
		&i.Name,
		&i.Bio,
	)
	return i, err
}
