// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artists.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addArtistArtwork = `-- name: AddArtistArtwork :exec
INSERT INTO "ArtistArtwork" ("id", "artistId", "imageUrl", "position")
VALUES ($1, $2, $3, $4)
`

type AddArtistArtworkParams struct {
	ID       string `json:"id"`
	ArtistId string `json:"artistId"`
	ImageUrl string `json:"imageUrl"`
	Position int32  `json:"position"`
}

func (q *Queries) AddArtistArtwork(ctx context.Context, arg AddArtistArtworkParams) error {
	_, err := q.db.Exec(ctx, addArtistArtwork,
		arg.ID,
		arg.ArtistId,
		arg.ImageUrl,
		arg.Position,
	)
	return err
}

const clearArtistArtworks = `-- name: ClearArtistArtworks :exec
DELETE FROM "ArtistArtwork" WHERE "artistId" = $1
`

func (q *Queries) ClearArtistArtworks(ctx context.Context, artistid string) error {
	_, err := q.db.Exec(ctx, clearArtistArtworks, artistid)
	return err
}

const createArtist = `-- name: CreateArtist :one
INSERT INTO "Artist" (
    "id", "slug", "city", "country", "featuredImageUrl", "avatarUrl", "status",
    "genre", "nationality", "facebookUrl", "twitterUrl", "youtubeUrl",
    "tiktokUrl", "websiteUrl", "spotifyUrl", "soundcloudUrl", "videoUrl",
    "createdAt", "updatedAt"
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, NOW(), NOW())
RETURNING id, slug, city, country, "avatarUrl", "featuredImageUrl", "instagramUrl", genre, nationality, "facebookUrl", "twitterUrl", "youtubeUrl", "tiktokUrl", "websiteUrl", "spotifyUrl", "soundcloudUrl", "videoUrl", status, "wpId", "createdAt", "updatedAt", "userId"
`

type CreateArtistParams struct {
	ID               string        `json:"id"`
	Slug             string        `json:"slug"`
	City             *string       `json:"city"`
	Country          *string       `json:"country"`
	FeaturedImageUrl *string       `json:"featuredImageUrl"`
	AvatarUrl        *string       `json:"avatarUrl"`
	Status           ProductStatus `json:"status"`
	Genre            *string       `json:"genre"`
	Nationality      *string       `json:"nationality"`
	FacebookUrl      *string       `json:"facebookUrl"`
	TwitterUrl       *string       `json:"twitterUrl"`
	YoutubeUrl       *string       `json:"youtubeUrl"`
	TiktokUrl        *string       `json:"tiktokUrl"`
	WebsiteUrl       *string       `json:"websiteUrl"`
	SpotifyUrl       *string       `json:"spotifyUrl"`
	SoundcloudUrl    *string       `json:"soundcloudUrl"`
	VideoUrl         *string       `json:"videoUrl"`
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist,
		arg.ID,
		arg.Slug,
		arg.City,
		arg.Country,
		arg.FeaturedImageUrl,
		arg.AvatarUrl,
		arg.Status,
		arg.Genre,
		arg.Nationality,
		arg.FacebookUrl,
		arg.TwitterUrl,
		arg.YoutubeUrl,
		arg.TiktokUrl,
		arg.WebsiteUrl,
		arg.SpotifyUrl,
		arg.SoundcloudUrl,
		arg.VideoUrl,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.City,
		&i.Country,
		&i.AvatarUrl,
		&i.FeaturedImageUrl,
		&i.InstagramUrl,
		&i.Genre,
		&i.Nationality,
		&i.FacebookUrl,
		&i.TwitterUrl,
		&i.YoutubeUrl,
		&i.TiktokUrl,
		&i.WebsiteUrl,
		&i.SpotifyUrl,
		&i.SoundcloudUrl,
		&i.VideoUrl,
		&i.Status,
		&i.WpId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserId,
	)
	return i, err
}

const deleteArtist = `-- name: DeleteArtist :exec
DELETE FROM "Artist" WHERE "id" = $1
`

func (q *Queries) DeleteArtist(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteArtist, id)
	return err
}

const deleteArtistArtworkOwned = `-- name: DeleteArtistArtworkOwned :execrows
DELETE FROM "ArtistArtwork" WHERE "id" = $1 AND "artistId" = $2
`

type DeleteArtistArtworkOwnedParams struct {
	ID       string `json:"id"`
	ArtistId string `json:"artistId"`
}

// Suppression d'une œuvre portant son propre contrôle d'appartenance : le
// prédicat sur artistId rend impossible la suppression de l'œuvre d'un autre.
func (q *Queries) DeleteArtistArtworkOwned(ctx context.Context, arg DeleteArtistArtworkOwnedParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArtistArtworkOwned, arg.ID, arg.ArtistId)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getArtistArtworks = `-- name: GetArtistArtworks :many
SELECT id, "artistId", "imageUrl", position FROM "ArtistArtwork" WHERE "artistId" = $1 ORDER BY "position" ASC
`

func (q *Queries) GetArtistArtworks(ctx context.Context, artistid string) ([]ArtistArtwork, error) {
	rows, err := q.db.Query(ctx, getArtistArtworks, artistid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtistArtwork{}
	for rows.Next() {
		var i ArtistArtwork
		if err := rows.Scan(
			&i.ID,
			&i.ArtistId,
			&i.ImageUrl,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistByID = `-- name: GetArtistByID :one
SELECT id, slug, city, country, "avatarUrl", "featuredImageUrl", "instagramUrl", genre, nationality, "facebookUrl", "twitterUrl", "youtubeUrl", "tiktokUrl", "websiteUrl", "spotifyUrl", "soundcloudUrl", "videoUrl", status, "wpId", "createdAt", "updatedAt", "userId" FROM "Artist" WHERE "id" = $1
`

func (q *Queries) GetArtistByID(ctx context.Context, id string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByID, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.City,
		&i.Country,
		&i.AvatarUrl,
		&i.FeaturedImageUrl,
		&i.InstagramUrl,
		&i.Genre,
		&i.Nationality,
		&i.FacebookUrl,
		&i.TwitterUrl,
		&i.YoutubeUrl,
		&i.TiktokUrl,
		&i.WebsiteUrl,
		&i.SpotifyUrl,
		&i.SoundcloudUrl,
		&i.VideoUrl,
		&i.Status,
		&i.WpId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserId,
	)
	return i, err
}

const getArtistBySlug = `-- name: GetArtistBySlug :one
SELECT id, slug, city, country, "avatarUrl", "featuredImageUrl", "instagramUrl", genre, nationality, "facebookUrl", "twitterUrl", "youtubeUrl", "tiktokUrl", "websiteUrl", "spotifyUrl", "soundcloudUrl", "videoUrl", status, "wpId", "createdAt", "updatedAt", "userId" FROM "Artist" WHERE "slug" = $1
`

func (q *Queries) GetArtistBySlug(ctx context.Context, slug string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistBySlug, slug)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.City,
		&i.Country,
		&i.AvatarUrl,
		&i.FeaturedImageUrl,
		&i.InstagramUrl,
		&i.Genre,
		&i.Nationality,
		&i.FacebookUrl,
		&i.TwitterUrl,
		&i.YoutubeUrl,
		&i.TiktokUrl,
		&i.WebsiteUrl,
		&i.SpotifyUrl,
		&i.SoundcloudUrl,
		&i.VideoUrl,
		&i.Status,
		&i.WpId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserId,
	)
	return i, err
}

const getArtistByUserID = `-- name: GetArtistByUserID :one
SELECT id, slug, city, country, "avatarUrl", "featuredImageUrl", "instagramUrl", genre, nationality, "facebookUrl", "twitterUrl", "youtubeUrl", "tiktokUrl", "websiteUrl", "spotifyUrl", "soundcloudUrl", "videoUrl", status, "wpId", "createdAt", "updatedAt", "userId" FROM "Artist" WHERE "userId" = $1
`

func (q *Queries) GetArtistByUserID(ctx context.Context, userid *string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByUserID, userid)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.City,
		&i.Country,
		&i.AvatarUrl,
		&i.FeaturedImageUrl,
		&i.InstagramUrl,
		&i.Genre,
		&i.Nationality,
		&i.FacebookUrl,
		&i.TwitterUrl,
		&i.YoutubeUrl,
		&i.TiktokUrl,
		&i.WebsiteUrl,
		&i.SpotifyUrl,
		&i.SoundcloudUrl,
		&i.VideoUrl,
		&i.Status,
		&i.WpId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserId,
	)
	return i, err
}

const getArtistTranslations = `-- name: GetArtistTranslations :many
SELECT id, "artistId", locale, name, bio FROM "ArtistTranslation" WHERE "artistId" = $1
`

func (q *Queries) GetArtistTranslations(ctx context.Context, artistid string) ([]ArtistTranslation, error) {
	rows, err := q.db.Query(ctx, getArtistTranslations, artistid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtistTranslation{}
	for rows.Next() {
		var i ArtistTranslation
		if err := rows.Scan(
			&i.ID,
			&i.ArtistId,
			&i.Locale,
			&i.Name,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkArtistUser = `-- name: LinkArtistUser :one
UPDATE "Artist" SET "userId" = $2, "updatedAt" = NOW() WHERE "id" = $1 RETURNING id, slug, city, country, "avatarUrl", "featuredImageUrl", "instagramUrl", genre, nationality, "facebookUrl", "twitterUrl", "youtubeUrl", "tiktokUrl", "websiteUrl", "spotifyUrl", "soundcloudUrl", "videoUrl", status, "wpId", "createdAt", "updatedAt", "userId"
`

type LinkArtistUserParams struct {
	ID     string  `json:"id"`
	UserId *string `json:"userId"`
}

func (q *Queries) LinkArtistUser(ctx context.Context, arg LinkArtistUserParams) (Artist, error) {
	row := q.db.QueryRow(ctx, linkArtistUser, arg.ID, arg.UserId)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.City,
		&i.Country,
		&i.AvatarUrl,
		&i.FeaturedImageUrl,
		&i.InstagramUrl,
		&i.Genre,
		&i.Nationality,
		&i.FacebookUrl,
		&i.TwitterUrl,
		&i.YoutubeUrl,
		&i.TiktokUrl,
		&i.WebsiteUrl,
		&i.SpotifyUrl,
		&i.SoundcloudUrl,
		&i.VideoUrl,
		&i.Status,
		&i.WpId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserId,
	)
	return i, err
}

const listArtists = `-- name: ListArtists :many
SELECT a.id, a.slug, a.city, a.country, a."avatarUrl", a."featuredImageUrl", a."instagramUrl", a.genre, a.nationality, a."facebookUrl", a."twitterUrl", a."youtubeUrl", a."tiktokUrl", a."websiteUrl", a."spotifyUrl", a."soundcloudUrl", a."videoUrl", a.status, a."wpId", a."createdAt", a."updatedAt", a."userId", COUNT(*) OVER() AS total_count
FROM "Artist" a
WHERE a."status" = 'PUBLISHED'::"ProductStatus"
ORDER BY a."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListArtistsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListArtistsRow struct {
	ID               string           `json:"id"`
	Slug             string           `json:"slug"`
	City             *string          `json:"city"`
	Country          *string          `json:"country"`
	AvatarUrl        *string          `json:"avatarUrl"`
	FeaturedImageUrl *string          `json:"featuredImageUrl"`
	InstagramUrl     *string          `json:"instagramUrl"`
	Genre            *string          `json:"genre"`
	Nationality      *string          `json:"nationality"`
	FacebookUrl      *string          `json:"facebookUrl"`
	TwitterUrl       *string          `json:"twitterUrl"`
	YoutubeUrl       *string          `json:"youtubeUrl"`
	TiktokUrl        *string          `json:"tiktokUrl"`
	WebsiteUrl       *string          `json:"websiteUrl"`
	SpotifyUrl       *string          `json:"spotifyUrl"`
	SoundcloudUrl    *string          `json:"soundcloudUrl"`
	VideoUrl         *string          `json:"videoUrl"`
	Status           ProductStatus    `json:"status"`
	WpId             *int32           `json:"wpId"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	UpdatedAt        pgtype.Timestamp `json:"updatedAt"`
	UserId           *string          `json:"userId"`
	TotalCount       int64            `json:"total_count"`
}

func (q *Queries) ListArtists(ctx context.Context, arg ListArtistsParams) ([]ListArtistsRow, error) {
	rows, err := q.db.Query(ctx, listArtists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtistsRow{}
	for rows.Next() {
		var i ListArtistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.City,
			&i.Country,
			&i.AvatarUrl,
			&i.FeaturedImageUrl,
			&i.InstagramUrl,
			&i.Genre,
			&i.Nationality,
			&i.FacebookUrl,
			&i.TwitterUrl,
			&i.YoutubeUrl,
			&i.TiktokUrl,
			&i.WebsiteUrl,
			&i.SpotifyUrl,
			&i.SoundcloudUrl,
			&i.VideoUrl,
			&i.Status,
			&i.WpId,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserId,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtist = `-- name: UpdateArtist :one
UPDATE "Artist"
SET "slug"          = COALESCE($2, "slug"),
    "city"          = COALESCE($3, "city"),
    "country"       = COALESCE($4, "country"),
    "featuredImageUrl" = COALESCE($5, "featuredImageUrl"),
    "avatarUrl"     = COALESCE($6, "avatarUrl"),
    "instagramUrl"  = COALESCE($7, "instagramUrl"),
    "genre"         = COALESCE($8, "genre"),
    "nationality"   = COALESCE($9, "nationality"),
    "facebookUrl"   = COALESCE($10, "facebookUrl"),
    "twitterUrl"    = COALESCE($11, "twitterUrl"),
    "youtubeUrl"    = COALESCE($12, "youtubeUrl"),
    "tiktokUrl"     = COALESCE($13, "tiktokUrl"),
    "websiteUrl"    = COALESCE($14, "websiteUrl"),
    "spotifyUrl"    = COALESCE($15, "spotifyUrl"),
    "soundcloudUrl" = COALESCE($16, "soundcloudUrl"),
    "videoUrl"      = COALESCE($17, "videoUrl"),
    "status"        = COALESCE($18::"ProductStatus", "status"),
    "updatedAt"     = NOW()
WHERE "id" = $1
RETURNING id, slug, city, country, "avatarUrl", "featuredImageUrl", "instagramUrl", genre, nationality, "facebookUrl", "twitterUrl", "youtubeUrl", "tiktokUrl", "websiteUrl", "spotifyUrl", "soundcloudUrl", "videoUrl", status, "wpId", "createdAt", "updatedAt", "userId"
`

type UpdateArtistParams struct {
	ID               string         `json:"id"`
	Slug             *string        `json:"slug"`
	City             *string        `json:"city"`
	Country          *string        `json:"country"`
	FeaturedImageUrl *string        `json:"featured_image_url"`
	AvatarUrl        *string        `json:"avatar_url"`
	InstagramUrl     *string        `json:"instagram_url"`
	Genre            *string        `json:"genre"`
	Nationality      *string        `json:"nationality"`
	FacebookUrl      *string        `json:"facebookUrl"`
	TwitterUrl       *string        `json:"twitterUrl"`
	YoutubeUrl       *string        `json:"youtubeUrl"`
	TiktokUrl        *string        `json:"tiktokUrl"`
	WebsiteUrl       *string        `json:"websiteUrl"`
	SpotifyUrl       *string        `json:"spotifyUrl"`
	SoundcloudUrl    *string        `json:"soundcloudUrl"`
	VideoUrl         *string        `json:"videoUrl"`
	Status           *ProductStatus `json:"status"`
}

func (q *Queries) UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, updateArtist,
		arg.ID,
		arg.Slug,
		arg.City,
		arg.Country,
		arg.FeaturedImageUrl,
		arg.AvatarUrl,
		arg.InstagramUrl,
		arg.Genre,
		arg.Nationality,
		arg.FacebookUrl,
		arg.TwitterUrl,
		arg.YoutubeUrl,
		arg.TiktokUrl,
		arg.WebsiteUrl,
		arg.SpotifyUrl,
		arg.SoundcloudUrl,
		arg.VideoUrl,
		arg.Status,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.City,
		&i.Country,
		&i.AvatarUrl,
		&i.FeaturedImageUrl,
		&i.InstagramUrl,
		&i.Genre,
		&i.Nationality,
		&i.FacebookUrl,
		&i.TwitterUrl,
		&i.YoutubeUrl,
		&i.TiktokUrl,
		&i.WebsiteUrl,
		&i.SpotifyUrl,
		&i.SoundcloudUrl,
		&i.VideoUrl,
		&i.Status,
		&i.WpId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserId,
	)
	return i, err
}

const upsertArtistTranslation = `-- name: UpsertArtistTranslation :one
INSERT INTO "ArtistTranslation" ("id", "artistId", "locale", "name", "bio")
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ("artistId", "locale") DO UPDATE
  SET "name" = EXCLUDED."name", "bio" = EXCLUDED."bio"
RETURNING id, "artistId", locale, name, bio
`

type UpsertArtistTranslationParams struct {
	ID       string  `json:"id"`
	ArtistId string  `json:"artistId"`
	Locale   Locale  `json:"locale"`
	Name     string  `json:"name"`
	Bio      *string `json:"bio"`
}

func (q *Queries) UpsertArtistTranslation(ctx context.Context, arg UpsertArtistTranslationParams) (ArtistTranslation, error) {
	row := q.db.QueryRow(ctx, upsertArtistTranslation,
		arg.ID,
		arg.ArtistId,
		arg.Locale,
		arg.Name,
		arg.Bio,
	)
	var i ArtistTranslation
	err := row.Scan(
		&i.ID,
		&i.ArtistId,
		&i.Locale,
		&i.Name,
		&i.Bio,
	)
	return i, err
}
