// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearResetToken = `-- name: ClearResetToken :exec
UPDATE "User"
SET "resetToken" = NULL, "resetTokenExpiry" = NULL, "passwordHash" = $2, "updatedAt" = NOW()
WHERE "id" = $1
`

type ClearResetTokenParams struct {
	ID           string `json:"id"`
	PasswordHash string `json:"passwordHash"`
}

func (q *Queries) ClearResetToken(ctx context.Context, arg ClearResetTokenParams) error {
	_, err := q.db.Exec(ctx, clearResetToken, arg.ID, arg.PasswordHash)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO "UserSession" ("id", "userId", "tokenHash", "expiresAt", "createdAt")
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, "userId", "tokenHash", "expiresAt", "createdAt"
`

type CreateSessionParams struct {
	ID        string           `json:"id"`
	UserId    string           `json:"userId"`
	TokenHash string           `json:"tokenHash"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserId,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "User" ("id", "email", "passwordHash", "firstName", "lastName", "phone", "role", "preferredLocale", "createdAt", "updatedAt", "emailVerified")
VALUES ($1, $2, $3, $4, $5, $6, 'CUSTOMER'::"UserRole", 'fr'::"Locale", NOW(), NOW(), false)
RETURNING id, email, "passwordHash", "firstName", "lastName", phone, role, "emailVerified", "preferredLocale", "wcId", "resetToken", "resetTokenExpiry", "emailVerificationToken", "emailVerificationTokenExpiry", "createdAt", "updatedAt", "artistClaimStatus", "artistClaimNote", "artistClaimAt"
`

type CreateUserParams struct {
	ID           string  `json:"id"`
	Email        string  `json:"email"`
	PasswordHash string  `json:"passwordHash"`
	FirstName    *string `json:"firstName"`
	LastName     *string `json:"lastName"`
	Phone        *string `json:"phone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.EmailVerified,
		&i.PreferredLocale,
		&i.WcId,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.EmailVerificationToken,
		&i.EmailVerificationTokenExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArtistClaimStatus,
		&i.ArtistClaimNote,
		&i.ArtistClaimAt,
	)
	return i, err
}

const createUserWithRole = `-- name: CreateUserWithRole :one
INSERT INTO "User" ("id", "email", "passwordHash", "firstName", "lastName", "phone", "role", "preferredLocale", "createdAt", "updatedAt", "emailVerified")
VALUES ($1, $2, $3, $4, $5, $6, $7::"UserRole", 'fr'::"Locale", NOW(), NOW(), false)
RETURNING id, email, "passwordHash", "firstName", "lastName", phone, role, "emailVerified", "preferredLocale", "wcId", "resetToken", "resetTokenExpiry", "emailVerificationToken", "emailVerificationTokenExpiry", "createdAt", "updatedAt", "artistClaimStatus", "artistClaimNote", "artistClaimAt"
`

type CreateUserWithRoleParams struct {
	ID           string   `json:"id"`
	Email        string   `json:"email"`
	PasswordHash string   `json:"passwordHash"`
	FirstName    *string  `json:"firstName"`
	LastName     *string  `json:"lastName"`
	Phone        *string  `json:"phone"`
	Column7      UserRole `json:"column_7"`
}

// CreateUser fige le rôle CUSTOMER ; cette variante sert au provisionnement des
// comptes artiste par un administrateur.
func (q *Queries) CreateUserWithRole(ctx context.Context, arg CreateUserWithRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithRole,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Column7,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.EmailVerified,
		&i.PreferredLocale,
		&i.WcId,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.EmailVerificationToken,
		&i.EmailVerificationTokenExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArtistClaimStatus,
		&i.ArtistClaimNote,
		&i.ArtistClaimAt,
	)
	return i, err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM "UserSession" WHERE "userId" = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userid string) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userid)
	return err
}

const getActiveSessionsByUser = `-- name: GetActiveSessionsByUser :many
SELECT id, "userId", "tokenHash", "expiresAt", "createdAt" FROM "UserSession"
WHERE "userId" = $1 AND "expiresAt" > NOW()
`

func (q *Queries) GetActiveSessionsByUser(ctx context.Context, userid string) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, getActiveSessionsByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSession{}
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, "passwordHash", "firstName", "lastName", phone, role, "emailVerified", "preferredLocale", "wcId", "resetToken", "resetTokenExpiry", "emailVerificationToken", "emailVerificationTokenExpiry", "createdAt", "updatedAt", "artistClaimStatus", "artistClaimNote", "artistClaimAt" FROM "User" WHERE "email" = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.EmailVerified,
		&i.PreferredLocale,
		&i.WcId,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.EmailVerificationToken,
		&i.EmailVerificationTokenExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArtistClaimStatus,
		&i.ArtistClaimNote,
		&i.ArtistClaimAt,
	)
	return i, err
}

const getUserByEmailVerificationToken = `-- name: GetUserByEmailVerificationToken :one
SELECT "id", "email", "emailVerified"
FROM "User"
WHERE "emailVerificationToken" = $1
  AND "emailVerificationTokenExpiry" > NOW()
`

type GetUserByEmailVerificationTokenRow struct {
	ID            string `json:"id"`
	Email         string `json:"email"`
	EmailVerified bool   `json:"emailVerified"`
}

func (q *Queries) GetUserByEmailVerificationToken(ctx context.Context, emailverificationtoken *string) (GetUserByEmailVerificationTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailVerificationToken, emailverificationtoken)
	var i GetUserByEmailVerificationTokenRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerified)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT "id", "email", "firstName", "lastName", "role", "preferredLocale", "createdAt", "emailVerified"
FROM "User" WHERE "id" = $1
`

type GetUserByIDRow struct {
	ID              string           `json:"id"`
	Email           string           `json:"email"`
	FirstName       *string          `json:"firstName"`
	LastName        *string          `json:"lastName"`
	Role            UserRole         `json:"role"`
	PreferredLocale Locale           `json:"preferredLocale"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	EmailVerified   bool             `json:"emailVerified"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.PreferredLocale,
		&i.CreatedAt,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByResetToken = `-- name: GetUserByResetToken :one
SELECT "id", "email", "role", "resetToken", "resetTokenExpiry", "emailVerified"
FROM "User" WHERE "resetToken" = $1 AND "resetTokenExpiry" > NOW()
`

type GetUserByResetTokenRow struct {
	ID               string           `json:"id"`
	Email            string           `json:"email"`
	Role             UserRole         `json:"role"`
	ResetToken       *string          `json:"resetToken"`
	ResetTokenExpiry pgtype.Timestamp `json:"resetTokenExpiry"`
	EmailVerified    bool             `json:"emailVerified"`
}

func (q *Queries) GetUserByResetToken(ctx context.Context, resettoken *string) (GetUserByResetTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserByResetToken, resettoken)
	var i GetUserByResetTokenRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.EmailVerified,
	)
	return i, err
}

const listArtistClaims = `-- name: ListArtistClaims :many
SELECT u."id", u."email", u."firstName", u."lastName", u."phone",
       u."role", u."artistClaimStatus", u."artistClaimNote", u."artistClaimAt",
       a."id" AS "linkedArtistId"
FROM "User" u
LEFT JOIN "Artist" a ON a."userId" = u."id"
WHERE u."artistClaimStatus" = $1::"ArtistClaimStatus"
ORDER BY u."artistClaimAt" DESC NULLS LAST
`

type ListArtistClaimsRow struct {
	ID                string            `json:"id"`
	Email             string            `json:"email"`
	FirstName         *string           `json:"firstName"`
	LastName          *string           `json:"lastName"`
	Phone             *string           `json:"phone"`
	Role              UserRole          `json:"role"`
	ArtistClaimStatus ArtistClaimStatus `json:"artistClaimStatus"`
	ArtistClaimNote   *string           `json:"artistClaimNote"`
	ArtistClaimAt     pgtype.Timestamp  `json:"artistClaimAt"`
	LinkedArtistId    *string           `json:"linkedArtistId"`
}

func (q *Queries) ListArtistClaims(ctx context.Context, status ArtistClaimStatus) ([]ListArtistClaimsRow, error) {
	rows, err := q.db.Query(ctx, listArtistClaims, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtistClaimsRow{}
	for rows.Next() {
		var i ListArtistClaimsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.Role,
			&i.ArtistClaimStatus,
			&i.ArtistClaimNote,
			&i.ArtistClaimAt,
			&i.LinkedArtistId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setArtistClaimStatus = `-- name: SetArtistClaimStatus :one
UPDATE "User"
SET "artistClaimStatus" = $2::"ArtistClaimStatus",
    "updatedAt"         = NOW()
WHERE "id" = $1
RETURNING id, email, "passwordHash", "firstName", "lastName", phone, role, "emailVerified", "preferredLocale", "wcId", "resetToken", "resetTokenExpiry", "emailVerificationToken", "emailVerificationTokenExpiry", "createdAt", "updatedAt", "artistClaimStatus", "artistClaimNote", "artistClaimAt"
`

type SetArtistClaimStatusParams struct {
	ID      string            `json:"id"`
	Column2 ArtistClaimStatus `json:"column_2"`
}

func (q *Queries) SetArtistClaimStatus(ctx context.Context, arg SetArtistClaimStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, setArtistClaimStatus, arg.ID, arg.Column2)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.EmailVerified,
		&i.PreferredLocale,
		&i.WcId,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.EmailVerificationToken,
		&i.EmailVerificationTokenExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArtistClaimStatus,
		&i.ArtistClaimNote,
		&i.ArtistClaimAt,
	)
	return i, err
}

const setEmailVerificationToken = `-- name: SetEmailVerificationToken :exec
UPDATE "User"
SET "emailVerificationToken" = $2, "emailVerificationTokenExpiry" = $3, "updatedAt" = NOW()
WHERE "id" = $1
`

type SetEmailVerificationTokenParams struct {
	ID                           string           `json:"id"`
	EmailVerificationToken       *string          `json:"emailVerificationToken"`
	EmailVerificationTokenExpiry pgtype.Timestamp `json:"emailVerificationTokenExpiry"`
}

func (q *Queries) SetEmailVerificationToken(ctx context.Context, arg SetEmailVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, setEmailVerificationToken, arg.ID, arg.EmailVerificationToken, arg.EmailVerificationTokenExpiry)
	return err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE "User"
SET "emailVerified" = true,
    "emailVerificationToken" = NULL,
    "emailVerificationTokenExpiry" = NULL,
    "updatedAt" = NOW()
WHERE "id" = $1
`

func (q *Queries) SetEmailVerified(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setEmailVerified, id)
	return err
}

const setPasswordResetToken = `-- name: SetPasswordResetToken :exec
UPDATE "User" SET "resetToken" = $2, "resetTokenExpiry" = $3, "updatedAt" = NOW()
WHERE "email" = $1
`

type SetPasswordResetTokenParams struct {
	Email            string           `json:"email"`
	ResetToken       *string          `json:"resetToken"`
	ResetTokenExpiry pgtype.Timestamp `json:"resetTokenExpiry"`
}

func (q *Queries) SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, setPasswordResetToken, arg.Email, arg.ResetToken, arg.ResetTokenExpiry)
	return err
}

const submitArtistClaim = `-- name: SubmitArtistClaim :one
UPDATE "User"
SET "artistClaimStatus" = 'PENDING'::"ArtistClaimStatus",
    "artistClaimNote"   = $2,
    "artistClaimAt"     = NOW(),
    "updatedAt"         = NOW()
WHERE "id" = $1
RETURNING id, email, "passwordHash", "firstName", "lastName", phone, role, "emailVerified", "preferredLocale", "wcId", "resetToken", "resetTokenExpiry", "emailVerificationToken", "emailVerificationTokenExpiry", "createdAt", "updatedAt", "artistClaimStatus", "artistClaimNote", "artistClaimAt"
`

type SubmitArtistClaimParams struct {
	ID              string  `json:"id"`
	ArtistClaimNote *string `json:"artistClaimNote"`
}

// Auto-déclaration « je suis un artiste RBS ». Idempotente : re-soumettre
// remplace la note et repasse en PENDING (utile après un refus).
func (q *Queries) SubmitArtistClaim(ctx context.Context, arg SubmitArtistClaimParams) (User, error) {
	row := q.db.QueryRow(ctx, submitArtistClaim, arg.ID, arg.ArtistClaimNote)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.EmailVerified,
		&i.PreferredLocale,
		&i.WcId,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.EmailVerificationToken,
		&i.EmailVerificationTokenExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArtistClaimStatus,
		&i.ArtistClaimNote,
		&i.ArtistClaimAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE "User" SET "role" = $2::"UserRole", "updatedAt" = NOW() WHERE "id" = $1 RETURNING id, email, "passwordHash", "firstName", "lastName", phone, role, "emailVerified", "preferredLocale", "wcId", "resetToken", "resetTokenExpiry", "emailVerificationToken", "emailVerificationTokenExpiry", "createdAt", "updatedAt", "artistClaimStatus", "artistClaimNote", "artistClaimAt"
`

type UpdateUserRoleParams struct {
	ID      string   `json:"id"`
	Column2 UserRole `json:"column_2"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Column2)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Role,
		&i.EmailVerified,
		&i.PreferredLocale,
		&i.WcId,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.EmailVerificationToken,
		&i.EmailVerificationTokenExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArtistClaimStatus,
		&i.ArtistClaimNote,
		&i.ArtistClaimAt,
	)
	return i, err
}
