// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO "Category" ("id", "slug", "parentId", "createdAt", "updatedAt")
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, slug, "parentId", "wpId", "createdAt", "updatedAt"
`

type CreateCategoryParams struct {
	ID       string  `json:"id"`
	Slug     string  `json:"slug"`
	ParentId *string `json:"parentId"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.ID, arg.Slug, arg.ParentId)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.ParentId,
		&i.WpId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM "Category" WHERE "id" = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, slug, "parentId", "wpId", "createdAt", "updatedAt" FROM "Category" WHERE "id" = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.ParentId,
		&i.WpId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, slug, "parentId", "wpId", "createdAt", "updatedAt" FROM "Category" WHERE "slug" = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.ParentId,
		&i.WpId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryTranslations = `-- name: GetCategoryTranslations :many
SELECT id, "categoryId", locale, name, description FROM "CategoryTranslation"
WHERE "categoryId" = $1 AND "locale" = $2
`

type GetCategoryTranslationsParams struct {
	CategoryId string `json:"categoryId"`
	Locale     Locale `json:"locale"`
}

func (q *Queries) GetCategoryTranslations(ctx context.Context, arg GetCategoryTranslationsParams) ([]CategoryTranslation, error) {
	rows, err := q.db.Query(ctx, getCategoryTranslations, arg.CategoryId, arg.Locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryTranslation{}
	for rows.Next() {
		var i CategoryTranslation
		if err := rows.Scan(
			&i.ID,
			&i.CategoryId,
			&i.Locale,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChildCategories = `-- name: GetChildCategories :many
SELECT c.id, c.slug, c."parentId", c."wpId", c."createdAt", c."updatedAt" FROM "Category" c WHERE c."parentId" = $1
`

func (q *Queries) GetChildCategories(ctx context.Context, parentid *string) ([]Category, error) {
	rows, err := q.db.Query(ctx, getChildCategories, parentid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.ParentId,
			&i.WpId,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT c.id, c.slug, c."parentId", c."wpId", c."createdAt", c."updatedAt", COUNT(*) OVER() AS total_count
FROM "Category" c
ORDER BY c."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListCategoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListCategoriesRow struct {
	ID         string           `json:"id"`
	Slug       string           `json:"slug"`
	ParentId   *string          `json:"parentId"`
	WpId       *int32           `json:"wpId"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
	TotalCount int64            `json:"total_count"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.ParentId,
			&i.WpId,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE "Category"
SET "slug" = COALESCE($2, "slug"),
    "parentId" = $3,
    "updatedAt" = NOW()
WHERE "id" = $1
RETURNING id, slug, "parentId", "wpId", "createdAt", "updatedAt"
`

type UpdateCategoryParams struct {
	ID       string  `json:"id"`
	Slug     *string `json:"slug"`
	ParentId *string `json:"parentId"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.Slug, arg.ParentId)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.ParentId,
		&i.WpId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCategoryTranslation = `-- name: UpsertCategoryTranslation :one
INSERT INTO "CategoryTranslation" ("id", "categoryId", "locale", "name", "description")
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ("categoryId", "locale") DO UPDATE
  SET "name" = EXCLUDED."name", "description" = EXCLUDED."description"
RETURNING id, "categoryId", locale, name, description
`

type UpsertCategoryTranslationParams struct {
	ID          string  `json:"id"`
	CategoryId  string  `json:"categoryId"`
	Locale      Locale  `json:"locale"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) UpsertCategoryTranslation(ctx context.Context, arg UpsertCategoryTranslationParams) (CategoryTranslation, error) {
	row := q.db.QueryRow(ctx, upsertCategoryTranslation,
		arg.ID,
		arg.CategoryId,
		arg.Locale,
		arg.Name,
		arg.Description,
	)
	var i CategoryTranslation
	err := row.Scan(
		&i.ID,
		&i.CategoryId,
		&i.Locale,
		&i.Name,
		&i.Description,
	)
	return i, err
}
