// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: festival.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFestivalEdition = `-- name: CreateFestivalEdition :one
INSERT INTO "FestivalEdition" ("id", "slug", "editionNumber", "year", "city", "country", "status", "mainImage", "heroImage", "gallery", "typography", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW(), NOW())
RETURNING id, slug, "editionNumber", year, city, country, status, "wpId", "mainImage", "heroImage", gallery, typography, "createdAt", "updatedAt"
`

type CreateFestivalEditionParams struct {
	ID            string        `json:"id"`
	Slug          string        `json:"slug"`
	EditionNumber int32         `json:"editionNumber"`
	Year          int32         `json:"year"`
	City          *string       `json:"city"`
	Country       string        `json:"country"`
	Status        ProductStatus `json:"status"`
	MainImage     *string       `json:"mainImage"`
	HeroImage     *string       `json:"heroImage"`
	Gallery       []byte        `json:"gallery"`
	Typography    []byte        `json:"typography"`
}

func (q *Queries) CreateFestivalEdition(ctx context.Context, arg CreateFestivalEditionParams) (FestivalEdition, error) {
	row := q.db.QueryRow(ctx, createFestivalEdition,
		arg.ID,
		arg.Slug,
		arg.EditionNumber,
		arg.Year,
		arg.City,
		arg.Country,
		arg.Status,
		arg.MainImage,
		arg.HeroImage,
		arg.Gallery,
		arg.Typography,
	)
	var i FestivalEdition
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.EditionNumber,
		&i.Year,
		&i.City,
		&i.Country,
		&i.Status,
		&i.WpId,
		&i.MainImage,
		&i.HeroImage,
		&i.Gallery,
		&i.Typography,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFestivalEdition = `-- name: DeleteFestivalEdition :exec
DELETE FROM "FestivalEdition" WHERE "id" = $1
`

func (q *Queries) DeleteFestivalEdition(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteFestivalEdition, id)
	return err
}

const getFestivalByID = `-- name: GetFestivalByID :one
SELECT id, slug, "editionNumber", year, city, country, status, "wpId", "mainImage", "heroImage", gallery, typography, "createdAt", "updatedAt" FROM "FestivalEdition" WHERE "id" = $1
`

func (q *Queries) GetFestivalByID(ctx context.Context, id string) (FestivalEdition, error) {
	row := q.db.QueryRow(ctx, getFestivalByID, id)
	var i FestivalEdition
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.EditionNumber,
		&i.Year,
		&i.City,
		&i.Country,
		&i.Status,
		&i.WpId,
		&i.MainImage,
		&i.HeroImage,
		&i.Gallery,
		&i.Typography,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFestivalBySlug = `-- name: GetFestivalBySlug :one
SELECT id, slug, "editionNumber", year, city, country, status, "wpId", "mainImage", "heroImage", gallery, typography, "createdAt", "updatedAt" FROM "FestivalEdition" WHERE "slug" = $1
`

func (q *Queries) GetFestivalBySlug(ctx context.Context, slug string) (FestivalEdition, error) {
	row := q.db.QueryRow(ctx, getFestivalBySlug, slug)
	var i FestivalEdition
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.EditionNumber,
		&i.Year,
		&i.City,
		&i.Country,
		&i.Status,
		&i.WpId,
		&i.MainImage,
		&i.HeroImage,
		&i.Gallery,
		&i.Typography,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFestivalTranslations = `-- name: GetFestivalTranslations :many
SELECT id, "festivalEditionId", locale, "themeName", summary, content FROM "FestivalTranslation" WHERE "festivalEditionId" = $1
`

func (q *Queries) GetFestivalTranslations(ctx context.Context, festivaleditionid string) ([]FestivalTranslation, error) {
	rows, err := q.db.Query(ctx, getFestivalTranslations, festivaleditionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FestivalTranslation{}
	for rows.Next() {
		var i FestivalTranslation
		if err := rows.Scan(
			&i.ID,
			&i.FestivalEditionId,
			&i.Locale,
			&i.ThemeName,
			&i.Summary,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFestivalEditions = `-- name: ListFestivalEditions :many
SELECT f.id, f.slug, f."editionNumber", f.year, f.city, f.country, f.status, f."wpId", f."mainImage", f."heroImage", f.gallery, f.typography, f."createdAt", f."updatedAt", COUNT(*) OVER() AS total_count
FROM "FestivalEdition" f
WHERE f."status" = 'PUBLISHED'::"ProductStatus"
ORDER BY f."year" DESC, f."editionNumber" DESC
LIMIT $1 OFFSET $2
`

type ListFestivalEditionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListFestivalEditionsRow struct {
	ID            string           `json:"id"`
	Slug          string           `json:"slug"`
	EditionNumber int32            `json:"editionNumber"`
	Year          int32            `json:"year"`
	City          *string          `json:"city"`
	Country       string           `json:"country"`
	Status        ProductStatus    `json:"status"`
	WpId          *int32           `json:"wpId"`
	MainImage     *string          `json:"mainImage"`
	HeroImage     *string          `json:"heroImage"`
	Gallery       []byte           `json:"gallery"`
	Typography    []byte           `json:"typography"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	UpdatedAt     pgtype.Timestamp `json:"updatedAt"`
	TotalCount    int64            `json:"total_count"`
}

func (q *Queries) ListFestivalEditions(ctx context.Context, arg ListFestivalEditionsParams) ([]ListFestivalEditionsRow, error) {
	rows, err := q.db.Query(ctx, listFestivalEditions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFestivalEditionsRow{}
	for rows.Next() {
		var i ListFestivalEditionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.EditionNumber,
			&i.Year,
			&i.City,
			&i.Country,
			&i.Status,
			&i.WpId,
			&i.MainImage,
			&i.HeroImage,
			&i.Gallery,
			&i.Typography,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFestivalEdition = `-- name: UpdateFestivalEdition :one
UPDATE "FestivalEdition"
SET "editionNumber" = COALESCE($2, "editionNumber"),
    "year"          = COALESCE($3, "year"),
    "city"          = COALESCE($4, "city"),
    "country"       = COALESCE($5, "country"),
    "status"        = COALESCE($6::"ProductStatus", "status"),
    "mainImage"     = COALESCE($7, "mainImage"),
    "heroImage"     = COALESCE($8, "heroImage"),
    "gallery"       = COALESCE($9, "gallery"),
    "typography"    = COALESCE($10, "typography"),
    "updatedAt"     = NOW()
WHERE "id" = $1
RETURNING id, slug, "editionNumber", year, city, country, status, "wpId", "mainImage", "heroImage", gallery, typography, "createdAt", "updatedAt"
`

type UpdateFestivalEditionParams struct {
	ID            string            `json:"id"`
	EditionNumber *int32            `json:"edition_number"`
	Year          *int32            `json:"year"`
	City          *string           `json:"city"`
	Country       *string           `json:"country"`
	Status        NullProductStatus `json:"status"`
	MainImage     *string           `json:"mainImage"`
	HeroImage     *string           `json:"heroImage"`
	Gallery       []byte            `json:"gallery"`
	Typography    []byte            `json:"typography"`
}

func (q *Queries) UpdateFestivalEdition(ctx context.Context, arg UpdateFestivalEditionParams) (FestivalEdition, error) {
	row := q.db.QueryRow(ctx, updateFestivalEdition,
		arg.ID,
		arg.EditionNumber,
		arg.Year,
		arg.City,
		arg.Country,
		arg.Status,
		arg.MainImage,
		arg.HeroImage,
		arg.Gallery,
		arg.Typography,
	)
	var i FestivalEdition
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.EditionNumber,
		&i.Year,
		&i.City,
		&i.Country,
		&i.Status,
		&i.WpId,
		&i.MainImage,
		&i.HeroImage,
		&i.Gallery,
		&i.Typography,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFestivalTranslation = `-- name: UpsertFestivalTranslation :one
INSERT INTO "FestivalTranslation" ("id", "festivalEditionId", "locale", "themeName", "summary", "content")
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT ("festivalEditionId", "locale") DO UPDATE
  SET "themeName" = EXCLUDED."themeName", "summary" = EXCLUDED."summary", "content" = EXCLUDED."content"
RETURNING id, "festivalEditionId", locale, "themeName", summary, content
`

type UpsertFestivalTranslationParams struct {
	ID                string  `json:"id"`
	FestivalEditionId string  `json:"festivalEditionId"`
	Locale            Locale  `json:"locale"`
	ThemeName         string  `json:"themeName"`
	Summary           *string `json:"summary"`
	Content           *string `json:"content"`
}

func (q *Queries) UpsertFestivalTranslation(ctx context.Context, arg UpsertFestivalTranslationParams) (FestivalTranslation, error) {
	row := q.db.QueryRow(ctx, upsertFestivalTranslation,
		arg.ID,
		arg.FestivalEditionId,
		arg.Locale,
		arg.ThemeName,
		arg.Summary,
		arg.Content,
	)
	var i FestivalTranslation
	err := row.Scan(
		&i.ID,
		&i.FestivalEditionId,
		&i.Locale,
		&i.ThemeName,
		&i.Summary,
		&i.Content,
	)
	return i, err
}
