// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

type Locale string

const (
	LocaleFr Locale = "fr"
	LocaleEn Locale = "en"
	LocaleDe Locale = "de"
	LocaleEs Locale = "es"
	LocaleIt Locale = "it"
)

func (e *Locale) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Locale(s)
	case string:
		*e = Locale(s)
	default:
		return fmt.Errorf("unsupported scan type for Locale: %T", src)
	}
	return nil
}

type NullLocale struct {
	Locale Locale `json:"Locale"`
	Valid  bool   `json:"valid"` // Valid is true if Locale is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLocale) Scan(value interface{}) error {
	if value == nil {
		ns.Locale, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Locale.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLocale) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Locale), nil
}

type OrderStatus string

const (
	OrderStatusPENDING    OrderStatus = "PENDING"
	OrderStatusPROCESSING OrderStatus = "PROCESSING"
	OrderStatusCOMPLETED  OrderStatus = "COMPLETED"
	OrderStatusCANCELLED  OrderStatus = "CANCELLED"
	OrderStatusREFUNDED   OrderStatus = "REFUNDED"
	OrderStatusFAILED     OrderStatus = "FAILED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"OrderStatus"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type PaymentMethod string

const (
	PaymentMethodSTRIPE      PaymentMethod = "STRIPE"
	PaymentMethodPAYPAL      PaymentMethod = "PAYPAL"
	PaymentMethodWAVE        PaymentMethod = "WAVE"
	PaymentMethodORANGEMONEY PaymentMethod = "ORANGE_MONEY"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"PaymentMethod"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PaymentStatus string

const (
	PaymentStatusUNPAID            PaymentStatus = "UNPAID"
	PaymentStatusPAID              PaymentStatus = "PAID"
	PaymentStatusPARTIALLYREFUNDED PaymentStatus = "PARTIALLY_REFUNDED"
	PaymentStatusREFUNDED          PaymentStatus = "REFUNDED"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"PaymentStatus"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type ProductStatus string

const (
	ProductStatusDRAFT     ProductStatus = "DRAFT"
	ProductStatusPUBLISHED ProductStatus = "PUBLISHED"
	ProductStatusARCHIVED  ProductStatus = "ARCHIVED"
)

func (e *ProductStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductStatus(s)
	case string:
		*e = ProductStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductStatus: %T", src)
	}
	return nil
}

type NullProductStatus struct {
	ProductStatus ProductStatus `json:"ProductStatus"`
	Valid         bool          `json:"valid"` // Valid is true if ProductStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductStatus), nil
}

type UserRole string

const (
	UserRoleCUSTOMER UserRole = "CUSTOMER"
	UserRoleADMIN    UserRole = "ADMIN"
	UserRoleEDITOR   UserRole = "EDITOR"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"UserRole"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Address struct {
	ID         string  `json:"id"`
	UserId     string  `json:"userId"`
	Label      *string `json:"label"`
	FirstName  string  `json:"firstName"`
	LastName   string  `json:"lastName"`
	Company    *string `json:"company"`
	Line1      string  `json:"line1"`
	Line2      *string `json:"line2"`
	City       string  `json:"city"`
	PostalCode string  `json:"postalCode"`
	Country    string  `json:"country"`
	IsDefault  bool    `json:"isDefault"`
}

type Artist struct {
	ID               string           `json:"id"`
	Slug             string           `json:"slug"`
	City             *string          `json:"city"`
	Country          *string          `json:"country"`
	Status           ProductStatus    `json:"status"`
	WpId             *int32           `json:"wpId"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	UpdatedAt        pgtype.Timestamp `json:"updatedAt"`
	AvatarUrl        *string          `json:"avatarUrl"`
	FeaturedImageUrl *string          `json:"featuredImageUrl"`
	InstagramUrl     *string          `json:"instagramUrl"`
}

type ArtistArtwork struct {
	ID       string `json:"id"`
	ArtistId string `json:"artistId"`
	Position int32  `json:"position"`
	ImageUrl string `json:"imageUrl"`
}

type ArtistTranslation struct {
	ID       string  `json:"id"`
	ArtistId string  `json:"artistId"`
	Locale   Locale  `json:"locale"`
	Name     string  `json:"name"`
	Bio      *string `json:"bio"`
}

type Category struct {
	ID        string           `json:"id"`
	Slug      string           `json:"slug"`
	ParentId  *string          `json:"parentId"`
	WpId      *int32           `json:"wpId"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type CategoryTranslation struct {
	ID          string  `json:"id"`
	CategoryId  string  `json:"categoryId"`
	Locale      Locale  `json:"locale"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type FestivalEdition struct {
	ID            string           `json:"id"`
	Slug          string           `json:"slug"`
	EditionNumber int32            `json:"editionNumber"`
	Year          int32            `json:"year"`
	City          *string          `json:"city"`
	Country       string           `json:"country"`
	Status        ProductStatus    `json:"status"`
	WpId          *int32           `json:"wpId"`
	MainImage     *string          `json:"mainImage"`
	HeroImage     *string          `json:"heroImage"`
	Gallery       []byte           `json:"gallery"`
	Typography    []byte           `json:"typography"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	UpdatedAt     pgtype.Timestamp `json:"updatedAt"`
}

type FestivalTranslation struct {
	ID                string  `json:"id"`
	FestivalEditionId string  `json:"festivalEditionId"`
	Locale            Locale  `json:"locale"`
	ThemeName         string  `json:"themeName"`
	Summary           *string `json:"summary"`
	Content           *string `json:"content"`
}

type Order struct {
	ID                    string            `json:"id"`
	OrderNumber           string            `json:"orderNumber"`
	UserId                *string           `json:"userId"`
	GuestEmail            *string           `json:"guestEmail"`
	Status                OrderStatus       `json:"status"`
	PaymentStatus         PaymentStatus     `json:"paymentStatus"`
	StripePaymentIntentId *string           `json:"stripePaymentIntentId"`
	Currency              string            `json:"currency"`
	Subtotal              decimal.Decimal   `json:"subtotal"`
	TaxAmount             decimal.Decimal   `json:"taxAmount"`
	ShippingAmount        decimal.Decimal   `json:"shippingAmount"`
	DiscountAmount        decimal.Decimal   `json:"discountAmount"`
	Total                 decimal.Decimal   `json:"total"`
	ShippingAddressId     *string           `json:"shippingAddressId"`
	BillingAddressId      *string           `json:"billingAddressId"`
	Notes                 *string           `json:"notes"`
	WcId                  *int32            `json:"wcId"`
	Locale                Locale            `json:"locale"`
	CreatedAt             pgtype.Timestamp  `json:"createdAt"`
	UpdatedAt             pgtype.Timestamp  `json:"updatedAt"`
	PaymentMethod         NullPaymentMethod `json:"paymentMethod"`
}

type OrderItem struct {
	ID          string          `json:"id"`
	OrderId     string          `json:"orderId"`
	ProductId   string          `json:"productId"`
	VariantId   *string         `json:"variantId"`
	Quantity    int32           `json:"quantity"`
	UnitPrice   decimal.Decimal `json:"unitPrice"`
	TotalPrice  decimal.Decimal `json:"totalPrice"`
	ProductName string          `json:"productName"`
	ProductSku  *string         `json:"productSku"`
}

type Page struct {
	ID        string           `json:"id"`
	Slug      string           `json:"slug"`
	Template  *string          `json:"template"`
	Status    ProductStatus    `json:"status"`
	WpId      *int32           `json:"wpId"`
	ParentId  *string          `json:"parentId"`
	MenuOrder int32            `json:"menuOrder"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type PageTranslation struct {
	ID              string  `json:"id"`
	PageId          string  `json:"pageId"`
	Locale          Locale  `json:"locale"`
	Title           string  `json:"title"`
	Slug            string  `json:"slug"`
	Content         string  `json:"content"`
	Excerpt         *string `json:"excerpt"`
	MetaTitle       *string `json:"metaTitle"`
	MetaDescription *string `json:"metaDescription"`
}

type Payment struct {
	ID         string           `json:"id"`
	OrderId    string           `json:"orderId"`
	Method     PaymentMethod    `json:"method"`
	ExternalId *string          `json:"externalId"`
	Amount     decimal.Decimal  `json:"amount"`
	Currency   string           `json:"currency"`
	Status     PaymentStatus    `json:"status"`
	Metadata   []byte           `json:"metadata"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
}

type PressMention struct {
	ID               string           `json:"id"`
	Title            string           `json:"title"`
	Source           string           `json:"source"`
	SourceUrl        string           `json:"sourceUrl"`
	LogoUrl          *string          `json:"logoUrl"`
	Excerpt          *string          `json:"excerpt"`
	Date             pgtype.Timestamp `json:"date"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	FeaturedImageUrl *string          `json:"featuredImageUrl"`
}

type Product struct {
	ID               string              `json:"id"`
	Slug             string              `json:"slug"`
	Sku              *string             `json:"sku"`
	Price            decimal.Decimal     `json:"price"`
	CompareAtPrice   decimal.NullDecimal `json:"compareAtPrice"`
	Stock            int32               `json:"stock"`
	ManageStock      bool                `json:"manageStock"`
	Status           ProductStatus       `json:"status"`
	WcId             *int32              `json:"wcId"`
	CreatedAt        pgtype.Timestamp    `json:"createdAt"`
	UpdatedAt        pgtype.Timestamp    `json:"updatedAt"`
	FeaturedImageUrl *string             `json:"featuredImageUrl"`
}

type ProductAttribute struct {
	ID        string `json:"id"`
	ProductId string `json:"productId"`
	Name      string `json:"name"`
	Value     string `json:"value"`
}

type ProductCategory struct {
	ProductId  string `json:"productId"`
	CategoryId string `json:"categoryId"`
}

type ProductImage struct {
	ID        string `json:"id"`
	ProductId string `json:"productId"`
	Position  int32  `json:"position"`
	ImageUrl  string `json:"imageUrl"`
}

type ProductTag struct {
	ProductId string `json:"productId"`
	TagId     string `json:"tagId"`
}

type ProductTranslation struct {
	ID               string  `json:"id"`
	ProductId        string  `json:"productId"`
	Locale           Locale  `json:"locale"`
	Name             string  `json:"name"`
	Description      *string `json:"description"`
	ShortDescription *string `json:"shortDescription"`
	Slug             string  `json:"slug"`
	MetaTitle        *string `json:"metaTitle"`
	MetaDescription  *string `json:"metaDescription"`
}

type ProductVariant struct {
	ID        string          `json:"id"`
	ProductId string          `json:"productId"`
	Sku       *string         `json:"sku"`
	Price     decimal.Decimal `json:"price"`
	Stock     int32           `json:"stock"`
	Options   []byte          `json:"options"`
	WcId      *int32          `json:"wcId"`
}

type Project struct {
	ID               string           `json:"id"`
	Slug             string           `json:"slug"`
	CompletedAt      pgtype.Timestamp `json:"completedAt"`
	ClientName       *string          `json:"clientName"`
	Status           ProductStatus    `json:"status"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	UpdatedAt        pgtype.Timestamp `json:"updatedAt"`
	FeaturedImageUrl *string          `json:"featuredImageUrl"`
}

type ProjectTranslation struct {
	ID              string  `json:"id"`
	ProjectId       string  `json:"projectId"`
	Locale          Locale  `json:"locale"`
	Title           string  `json:"title"`
	Summary         *string `json:"summary"`
	Content         *string `json:"content"`
	MetaTitle       *string `json:"metaTitle"`
	MetaDescription *string `json:"metaDescription"`
}

type Quote struct {
	ID           string           `json:"id"`
	Name         string           `json:"name"`
	Surname      *string          `json:"surname"`
	Email        string           `json:"email"`
	Phone        *string          `json:"phone"`
	Company      *string          `json:"company"`
	OrderType    string           `json:"orderType"`
	Quantity     *int32           `json:"quantity"`
	DeliveryDate pgtype.Timestamp `json:"deliveryDate"`
	Message      string           `json:"message"`
	Status       string           `json:"status"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
}

type Service struct {
	ID        string           `json:"id"`
	Slug      string           `json:"slug"`
	Icon      *string          `json:"icon"`
	Status    ProductStatus    `json:"status"`
	MenuOrder int32            `json:"menuOrder"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type ServiceTranslation struct {
	ID              string  `json:"id"`
	ServiceId       string  `json:"serviceId"`
	Locale          Locale  `json:"locale"`
	Title           string  `json:"title"`
	Description     string  `json:"description"`
	MetaTitle       *string `json:"metaTitle"`
	MetaDescription *string `json:"metaDescription"`
}

type Tag struct {
	ID        string           `json:"id"`
	Slug      string           `json:"slug"`
	WpId      *int32           `json:"wpId"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type TagTranslation struct {
	ID     string `json:"id"`
	TagId  string `json:"tagId"`
	Locale Locale `json:"locale"`
	Name   string `json:"name"`
}

type User struct {
	ID                           string           `json:"id"`
	Email                        string           `json:"email"`
	PasswordHash                 string           `json:"passwordHash"`
	FirstName                    *string          `json:"firstName"`
	LastName                     *string          `json:"lastName"`
	Phone                        *string          `json:"phone"`
	Role                         UserRole         `json:"role"`
	EmailVerified                bool             `json:"emailVerified"`
	PreferredLocale              Locale           `json:"preferredLocale"`
	WcId                         *int32           `json:"wcId"`
	CreatedAt                    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt                    pgtype.Timestamp `json:"updatedAt"`
	ResetToken                   *string          `json:"resetToken"`
	ResetTokenExpiry             pgtype.Timestamp `json:"resetTokenExpiry"`
	EmailVerificationToken       *string          `json:"emailVerificationToken"`
	EmailVerificationTokenExpiry pgtype.Timestamp `json:"emailVerificationTokenExpiry"`
}

type UserSession struct {
	ID        string           `json:"id"`
	UserId    string           `json:"userId"`
	TokenHash string           `json:"tokenHash"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}
