// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO "Order" ("id", "orderNumber", "userId", "guestEmail", "status", "paymentStatus",
                     "currency", "subtotal", "taxAmount", "shippingAmount", "discountAmount",
                     "total", "shippingAddressId", "billingAddressId", "notes", "locale", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, 'PENDING'::"OrderStatus", 'UNPAID'::"PaymentStatus",
        'XOF', $5, 0, 0, 0, $5, $6, $7, $8, 'fr'::"Locale", NOW(), NOW())
RETURNING id, "orderNumber", "userId", "guestEmail", status, "paymentStatus", "stripePaymentIntentId", currency, subtotal, "taxAmount", "shippingAmount", "discountAmount", total, "shippingAddressId", "billingAddressId", notes, "wcId", locale, "createdAt", "updatedAt"
`

type CreateOrderParams struct {
	ID                string          `json:"id"`
	OrderNumber       string          `json:"orderNumber"`
	UserId            *string         `json:"userId"`
	GuestEmail        *string         `json:"guestEmail"`
	Subtotal          decimal.Decimal `json:"subtotal"`
	ShippingAddressId *string         `json:"shippingAddressId"`
	BillingAddressId  *string         `json:"billingAddressId"`
	Notes             *string         `json:"notes"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.OrderNumber,
		arg.UserId,
		arg.GuestEmail,
		arg.Subtotal,
		arg.ShippingAddressId,
		arg.BillingAddressId,
		arg.Notes,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserId,
		&i.GuestEmail,
		&i.Status,
		&i.PaymentStatus,
		&i.StripePaymentIntentId,
		&i.Currency,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ShippingAmount,
		&i.DiscountAmount,
		&i.Total,
		&i.ShippingAddressId,
		&i.BillingAddressId,
		&i.Notes,
		&i.WcId,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO "OrderItem" ("id", "orderId", "productId", "variantId", "quantity", "unitPrice", "totalPrice", "productName", "productSku")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, "orderId", "productId", "variantId", quantity, "unitPrice", "totalPrice", "productName", "productSku"
`

type CreateOrderItemParams struct {
	ID          string          `json:"id"`
	OrderId     string          `json:"orderId"`
	ProductId   string          `json:"productId"`
	VariantId   *string         `json:"variantId"`
	Quantity    int32           `json:"quantity"`
	UnitPrice   decimal.Decimal `json:"unitPrice"`
	TotalPrice  decimal.Decimal `json:"totalPrice"`
	ProductName string          `json:"productName"`
	ProductSku  *string         `json:"productSku"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.ID,
		arg.OrderId,
		arg.ProductId,
		arg.VariantId,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalPrice,
		arg.ProductName,
		arg.ProductSku,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderId,
		&i.ProductId,
		&i.VariantId,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.ProductName,
		&i.ProductSku,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, "orderNumber", "userId", "guestEmail", status, "paymentStatus", "stripePaymentIntentId", currency, subtotal, "taxAmount", "shippingAmount", "discountAmount", total, "shippingAddressId", "billingAddressId", notes, "wcId", locale, "createdAt", "updatedAt" FROM "Order" WHERE "id" = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserId,
		&i.GuestEmail,
		&i.Status,
		&i.PaymentStatus,
		&i.StripePaymentIntentId,
		&i.Currency,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ShippingAmount,
		&i.DiscountAmount,
		&i.Total,
		&i.ShippingAddressId,
		&i.BillingAddressId,
		&i.Notes,
		&i.WcId,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT id, "orderId", "productId", "variantId", quantity, "unitPrice", "totalPrice", "productName", "productSku" FROM "OrderItem" WHERE "orderId" = $1
`

func (q *Queries) GetOrderItems(ctx context.Context, orderid string) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderId,
			&i.ProductId,
			&i.VariantId,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalPrice,
			&i.ProductName,
			&i.ProductSku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductForOrder = `-- name: GetProductForOrder :one
SELECT "id", "sku", "price", "stock", "manageStock" FROM "Product" WHERE "id" = $1
`

type GetProductForOrderRow struct {
	ID          string          `json:"id"`
	Sku         *string         `json:"sku"`
	Price       decimal.Decimal `json:"price"`
	Stock       int32           `json:"stock"`
	ManageStock bool            `json:"manageStock"`
}

func (q *Queries) GetProductForOrder(ctx context.Context, id string) (GetProductForOrderRow, error) {
	row := q.db.QueryRow(ctx, getProductForOrder, id)
	var i GetProductForOrderRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Price,
		&i.Stock,
		&i.ManageStock,
	)
	return i, err
}

const listMyOrders = `-- name: ListMyOrders :many
SELECT id, "orderNumber", "userId", "guestEmail", status, "paymentStatus", "stripePaymentIntentId", currency, subtotal, "taxAmount", "shippingAmount", "discountAmount", total, "shippingAddressId", "billingAddressId", notes, "wcId", locale, "createdAt", "updatedAt", COUNT(*) OVER() AS total_count
FROM "Order"
WHERE "userId" = $1
ORDER BY "createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListMyOrdersParams struct {
	UserId *string `json:"userId"`
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
}

type ListMyOrdersRow struct {
	ID                    string           `json:"id"`
	OrderNumber           string           `json:"orderNumber"`
	UserId                *string          `json:"userId"`
	GuestEmail            *string          `json:"guestEmail"`
	Status                OrderStatus      `json:"status"`
	PaymentStatus         PaymentStatus    `json:"paymentStatus"`
	StripePaymentIntentId *string          `json:"stripePaymentIntentId"`
	Currency              string           `json:"currency"`
	Subtotal              decimal.Decimal  `json:"subtotal"`
	TaxAmount             decimal.Decimal  `json:"taxAmount"`
	ShippingAmount        decimal.Decimal  `json:"shippingAmount"`
	DiscountAmount        decimal.Decimal  `json:"discountAmount"`
	Total                 decimal.Decimal  `json:"total"`
	ShippingAddressId     *string          `json:"shippingAddressId"`
	BillingAddressId      *string          `json:"billingAddressId"`
	Notes                 *string          `json:"notes"`
	WcId                  *int32           `json:"wcId"`
	Locale                Locale           `json:"locale"`
	CreatedAt             pgtype.Timestamp `json:"createdAt"`
	UpdatedAt             pgtype.Timestamp `json:"updatedAt"`
	TotalCount            int64            `json:"total_count"`
}

func (q *Queries) ListMyOrders(ctx context.Context, arg ListMyOrdersParams) ([]ListMyOrdersRow, error) {
	rows, err := q.db.Query(ctx, listMyOrders, arg.UserId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyOrdersRow{}
	for rows.Next() {
		var i ListMyOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserId,
			&i.GuestEmail,
			&i.Status,
			&i.PaymentStatus,
			&i.StripePaymentIntentId,
			&i.Currency,
			&i.Subtotal,
			&i.TaxAmount,
			&i.ShippingAmount,
			&i.DiscountAmount,
			&i.Total,
			&i.ShippingAddressId,
			&i.BillingAddressId,
			&i.Notes,
			&i.WcId,
			&i.Locale,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, "orderNumber", "userId", "guestEmail", status, "paymentStatus", "stripePaymentIntentId", currency, subtotal, "taxAmount", "shippingAmount", "discountAmount", total, "shippingAddressId", "billingAddressId", notes, "wcId", locale, "createdAt", "updatedAt", COUNT(*) OVER() AS total_count
FROM "Order"
ORDER BY "createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListOrdersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListOrdersRow struct {
	ID                    string           `json:"id"`
	OrderNumber           string           `json:"orderNumber"`
	UserId                *string          `json:"userId"`
	GuestEmail            *string          `json:"guestEmail"`
	Status                OrderStatus      `json:"status"`
	PaymentStatus         PaymentStatus    `json:"paymentStatus"`
	StripePaymentIntentId *string          `json:"stripePaymentIntentId"`
	Currency              string           `json:"currency"`
	Subtotal              decimal.Decimal  `json:"subtotal"`
	TaxAmount             decimal.Decimal  `json:"taxAmount"`
	ShippingAmount        decimal.Decimal  `json:"shippingAmount"`
	DiscountAmount        decimal.Decimal  `json:"discountAmount"`
	Total                 decimal.Decimal  `json:"total"`
	ShippingAddressId     *string          `json:"shippingAddressId"`
	BillingAddressId      *string          `json:"billingAddressId"`
	Notes                 *string          `json:"notes"`
	WcId                  *int32           `json:"wcId"`
	Locale                Locale           `json:"locale"`
	CreatedAt             pgtype.Timestamp `json:"createdAt"`
	UpdatedAt             pgtype.Timestamp `json:"updatedAt"`
	TotalCount            int64            `json:"total_count"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersRow{}
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserId,
			&i.GuestEmail,
			&i.Status,
			&i.PaymentStatus,
			&i.StripePaymentIntentId,
			&i.Currency,
			&i.Subtotal,
			&i.TaxAmount,
			&i.ShippingAmount,
			&i.DiscountAmount,
			&i.Total,
			&i.ShippingAddressId,
			&i.BillingAddressId,
			&i.Notes,
			&i.WcId,
			&i.Locale,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE "Order"
SET "status" = $2::"OrderStatus", "updatedAt" = NOW()
WHERE "id" = $1
RETURNING id, "orderNumber", "userId", "guestEmail", status, "paymentStatus", "stripePaymentIntentId", currency, subtotal, "taxAmount", "shippingAmount", "discountAmount", total, "shippingAddressId", "billingAddressId", notes, "wcId", locale, "createdAt", "updatedAt"
`

type UpdateOrderStatusParams struct {
	ID     string      `json:"id"`
	Status OrderStatus `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserId,
		&i.GuestEmail,
		&i.Status,
		&i.PaymentStatus,
		&i.StripePaymentIntentId,
		&i.Currency,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ShippingAmount,
		&i.DiscountAmount,
		&i.Total,
		&i.ShippingAddressId,
		&i.BillingAddressId,
		&i.Notes,
		&i.WcId,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
