// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPage = `-- name: CreatePage :one
INSERT INTO "Page" ("id", "slug", "template", "status", "parentId", "menuOrder", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
RETURNING id, slug, template, status, "wpId", "parentId", "menuOrder", "createdAt", "updatedAt"
`

type CreatePageParams struct {
	ID        string        `json:"id"`
	Slug      string        `json:"slug"`
	Template  *string       `json:"template"`
	Status    ProductStatus `json:"status"`
	ParentId  *string       `json:"parentId"`
	MenuOrder int32         `json:"menuOrder"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.ID,
		arg.Slug,
		arg.Template,
		arg.Status,
		arg.ParentId,
		arg.MenuOrder,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Template,
		&i.Status,
		&i.WpId,
		&i.ParentId,
		&i.MenuOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM "Page" WHERE "id" = $1
`

func (q *Queries) DeletePage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePage, id)
	return err
}

const getPageByID = `-- name: GetPageByID :one
SELECT id, slug, template, status, "wpId", "parentId", "menuOrder", "createdAt", "updatedAt" FROM "Page" WHERE "id" = $1
`

func (q *Queries) GetPageByID(ctx context.Context, id string) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByID, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Template,
		&i.Status,
		&i.WpId,
		&i.ParentId,
		&i.MenuOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageBySlug = `-- name: GetPageBySlug :one
SELECT id, slug, template, status, "wpId", "parentId", "menuOrder", "createdAt", "updatedAt" FROM "Page" WHERE "slug" = $1
`

func (q *Queries) GetPageBySlug(ctx context.Context, slug string) (Page, error) {
	row := q.db.QueryRow(ctx, getPageBySlug, slug)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Template,
		&i.Status,
		&i.WpId,
		&i.ParentId,
		&i.MenuOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageTranslationByLocale = `-- name: GetPageTranslationByLocale :one
SELECT id, "pageId", locale, title, slug, content, excerpt, "metaTitle", "metaDescription" FROM "PageTranslation" WHERE "pageId" = $1 AND "locale" = $2
`

type GetPageTranslationByLocaleParams struct {
	PageId string `json:"pageId"`
	Locale Locale `json:"locale"`
}

func (q *Queries) GetPageTranslationByLocale(ctx context.Context, arg GetPageTranslationByLocaleParams) (PageTranslation, error) {
	row := q.db.QueryRow(ctx, getPageTranslationByLocale, arg.PageId, arg.Locale)
	var i PageTranslation
	err := row.Scan(
		&i.ID,
		&i.PageId,
		&i.Locale,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.MetaTitle,
		&i.MetaDescription,
	)
	return i, err
}

const getPageTranslations = `-- name: GetPageTranslations :many
SELECT id, "pageId", locale, title, slug, content, excerpt, "metaTitle", "metaDescription" FROM "PageTranslation" WHERE "pageId" = $1
`

func (q *Queries) GetPageTranslations(ctx context.Context, pageid string) ([]PageTranslation, error) {
	rows, err := q.db.Query(ctx, getPageTranslations, pageid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageTranslation{}
	for rows.Next() {
		var i PageTranslation
		if err := rows.Scan(
			&i.ID,
			&i.PageId,
			&i.Locale,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Excerpt,
			&i.MetaTitle,
			&i.MetaDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPages = `-- name: ListPages :many
SELECT p.id, p.slug, p.template, p.status, p."wpId", p."parentId", p."menuOrder", p."createdAt", p."updatedAt", COUNT(*) OVER() AS total_count
FROM "Page" p
WHERE p."status" = 'PUBLISHED'::"ProductStatus"
ORDER BY p."menuOrder" ASC, p."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListPagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPagesRow struct {
	ID         string           `json:"id"`
	Slug       string           `json:"slug"`
	Template   *string          `json:"template"`
	Status     ProductStatus    `json:"status"`
	WpId       *int32           `json:"wpId"`
	ParentId   *string          `json:"parentId"`
	MenuOrder  int32            `json:"menuOrder"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
	TotalCount int64            `json:"total_count"`
}

func (q *Queries) ListPages(ctx context.Context, arg ListPagesParams) ([]ListPagesRow, error) {
	rows, err := q.db.Query(ctx, listPages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPagesRow{}
	for rows.Next() {
		var i ListPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Template,
			&i.Status,
			&i.WpId,
			&i.ParentId,
			&i.MenuOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePage = `-- name: UpdatePage :one
UPDATE "Page"
SET "template" = COALESCE($2, "template"),
    "status" = COALESCE($3::"ProductStatus", "status"),
    "menuOrder" = COALESCE($4::int, "menuOrder"),
    "updatedAt" = NOW()
WHERE "id" = $1
RETURNING id, slug, template, status, "wpId", "parentId", "menuOrder", "createdAt", "updatedAt"
`

type UpdatePageParams struct {
	ID        string         `json:"id"`
	Template  *string        `json:"template"`
	Status    *ProductStatus `json:"status"`
	MenuOrder *int32         `json:"menu_order"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, updatePage,
		arg.ID,
		arg.Template,
		arg.Status,
		arg.MenuOrder,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Template,
		&i.Status,
		&i.WpId,
		&i.ParentId,
		&i.MenuOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPageTranslation = `-- name: UpsertPageTranslation :one
INSERT INTO "PageTranslation" ("id", "pageId", "locale", "title", "slug", "content", "excerpt", "metaTitle", "metaDescription")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT ("pageId", "locale") DO UPDATE
  SET "title" = EXCLUDED."title", "slug" = EXCLUDED."slug",
      "content" = EXCLUDED."content", "excerpt" = EXCLUDED."excerpt",
      "metaTitle" = EXCLUDED."metaTitle", "metaDescription" = EXCLUDED."metaDescription"
RETURNING id, "pageId", locale, title, slug, content, excerpt, "metaTitle", "metaDescription"
`

type UpsertPageTranslationParams struct {
	ID              string  `json:"id"`
	PageId          string  `json:"pageId"`
	Locale          Locale  `json:"locale"`
	Title           string  `json:"title"`
	Slug            string  `json:"slug"`
	Content         string  `json:"content"`
	Excerpt         *string `json:"excerpt"`
	MetaTitle       *string `json:"metaTitle"`
	MetaDescription *string `json:"metaDescription"`
}

func (q *Queries) UpsertPageTranslation(ctx context.Context, arg UpsertPageTranslationParams) (PageTranslation, error) {
	row := q.db.QueryRow(ctx, upsertPageTranslation,
		arg.ID,
		arg.PageId,
		arg.Locale,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Excerpt,
		arg.MetaTitle,
		arg.MetaDescription,
	)
	var i PageTranslation
	err := row.Scan(
		&i.ID,
		&i.PageId,
		&i.Locale,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.MetaTitle,
		&i.MetaDescription,
	)
	return i, err
}
