// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package db

import (
	"context"
)

const getOrderByStripeSession = `-- name: GetOrderByStripeSession :one
SELECT id, "orderNumber", "userId", "guestEmail", status, "paymentStatus", "stripePaymentIntentId", currency, subtotal, "taxAmount", "shippingAmount", "discountAmount", total, "shippingAddressId", "billingAddressId", notes, "wcId", locale, "createdAt", "updatedAt" FROM "Order" WHERE "stripePaymentIntentId" = $1
`

func (q *Queries) GetOrderByStripeSession(ctx context.Context, stripepaymentintentid *string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByStripeSession, stripepaymentintentid)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserId,
		&i.GuestEmail,
		&i.Status,
		&i.PaymentStatus,
		&i.StripePaymentIntentId,
		&i.Currency,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ShippingAmount,
		&i.DiscountAmount,
		&i.Total,
		&i.ShippingAddressId,
		&i.BillingAddressId,
		&i.Notes,
		&i.WcId,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderPaymentStatus = `-- name: UpdateOrderPaymentStatus :one
UPDATE "Order"
SET "paymentStatus" = $2::"PaymentStatus",
    "status" = COALESCE($3::"OrderStatus", "status"),
    "stripePaymentIntentId" = COALESCE($4::text, "stripePaymentIntentId"),
    "updatedAt" = NOW()
WHERE "id" = $1
RETURNING id, "orderNumber", "userId", "guestEmail", status, "paymentStatus", "stripePaymentIntentId", currency, subtotal, "taxAmount", "shippingAmount", "discountAmount", total, "shippingAddressId", "billingAddressId", notes, "wcId", locale, "createdAt", "updatedAt"
`

type UpdateOrderPaymentStatusParams struct {
	ID                    string          `json:"id"`
	Column2               PaymentStatus   `json:"column_2"`
	Status                NullOrderStatus `json:"status"`
	StripePaymentIntentId *string         `json:"stripePaymentIntentId"`
}

func (q *Queries) UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderPaymentStatus,
		arg.ID,
		arg.Column2,
		arg.Status,
		arg.StripePaymentIntentId,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserId,
		&i.GuestEmail,
		&i.Status,
		&i.PaymentStatus,
		&i.StripePaymentIntentId,
		&i.Currency,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ShippingAmount,
		&i.DiscountAmount,
		&i.Total,
		&i.ShippingAddressId,
		&i.BillingAddressId,
		&i.Notes,
		&i.WcId,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
