// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: press.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPressMention = `-- name: CreatePressMention :one
INSERT INTO "PressMention" ("id", "title", "source", "sourceUrl", "logoUrl", "featuredImageUrl", "excerpt", "date", "createdAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
RETURNING id, title, source, "sourceUrl", "logoUrl", excerpt, date, "createdAt", "featuredImageUrl"
`

type CreatePressMentionParams struct {
	ID               string           `json:"id"`
	Title            string           `json:"title"`
	Source           string           `json:"source"`
	SourceUrl        string           `json:"sourceUrl"`
	LogoUrl          *string          `json:"logoUrl"`
	FeaturedImageUrl *string          `json:"featuredImageUrl"`
	Excerpt          *string          `json:"excerpt"`
	Date             pgtype.Timestamp `json:"date"`
}

func (q *Queries) CreatePressMention(ctx context.Context, arg CreatePressMentionParams) (PressMention, error) {
	row := q.db.QueryRow(ctx, createPressMention,
		arg.ID,
		arg.Title,
		arg.Source,
		arg.SourceUrl,
		arg.LogoUrl,
		arg.FeaturedImageUrl,
		arg.Excerpt,
		arg.Date,
	)
	var i PressMention
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.SourceUrl,
		&i.LogoUrl,
		&i.Excerpt,
		&i.Date,
		&i.CreatedAt,
		&i.FeaturedImageUrl,
	)
	return i, err
}

const deletePressMention = `-- name: DeletePressMention :exec
DELETE FROM "PressMention" WHERE "id" = $1
`

func (q *Queries) DeletePressMention(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePressMention, id)
	return err
}

const getPressMentionByID = `-- name: GetPressMentionByID :one
SELECT id, title, source, "sourceUrl", "logoUrl", excerpt, date, "createdAt", "featuredImageUrl" FROM "PressMention" WHERE "id" = $1
`

func (q *Queries) GetPressMentionByID(ctx context.Context, id string) (PressMention, error) {
	row := q.db.QueryRow(ctx, getPressMentionByID, id)
	var i PressMention
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.SourceUrl,
		&i.LogoUrl,
		&i.Excerpt,
		&i.Date,
		&i.CreatedAt,
		&i.FeaturedImageUrl,
	)
	return i, err
}

const listPressMentions = `-- name: ListPressMentions :many
SELECT id, title, source, "sourceUrl", "logoUrl", excerpt, date, "createdAt", "featuredImageUrl", COUNT(*) OVER() AS total_count
FROM "PressMention"
ORDER BY "date" DESC NULLS LAST, "createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListPressMentionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPressMentionsRow struct {
	ID               string           `json:"id"`
	Title            string           `json:"title"`
	Source           string           `json:"source"`
	SourceUrl        string           `json:"sourceUrl"`
	LogoUrl          *string          `json:"logoUrl"`
	Excerpt          *string          `json:"excerpt"`
	Date             pgtype.Timestamp `json:"date"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	FeaturedImageUrl *string          `json:"featuredImageUrl"`
	TotalCount       int64            `json:"total_count"`
}

func (q *Queries) ListPressMentions(ctx context.Context, arg ListPressMentionsParams) ([]ListPressMentionsRow, error) {
	rows, err := q.db.Query(ctx, listPressMentions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPressMentionsRow{}
	for rows.Next() {
		var i ListPressMentionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Source,
			&i.SourceUrl,
			&i.LogoUrl,
			&i.Excerpt,
			&i.Date,
			&i.CreatedAt,
			&i.FeaturedImageUrl,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePressMention = `-- name: UpdatePressMention :one
UPDATE "PressMention"
SET "title" = COALESCE($2, "title"),
    "source" = COALESCE($3, "source"),
    "sourceUrl" = COALESCE($4, "sourceUrl"),
    "logoUrl" = $5,
    "featuredImageUrl" = $6,
    "excerpt" = $7,
    "date" = $8
WHERE "id" = $1
RETURNING id, title, source, "sourceUrl", "logoUrl", excerpt, date, "createdAt", "featuredImageUrl"
`

type UpdatePressMentionParams struct {
	ID               string           `json:"id"`
	Title            *string          `json:"title"`
	Source           *string          `json:"source"`
	SourceUrl        *string          `json:"source_url"`
	LogoUrl          *string          `json:"logo_url"`
	FeaturedImageUrl *string          `json:"featured_image_url"`
	Excerpt          *string          `json:"excerpt"`
	Date             pgtype.Timestamp `json:"date"`
}

func (q *Queries) UpdatePressMention(ctx context.Context, arg UpdatePressMentionParams) (PressMention, error) {
	row := q.db.QueryRow(ctx, updatePressMention,
		arg.ID,
		arg.Title,
		arg.Source,
		arg.SourceUrl,
		arg.LogoUrl,
		arg.FeaturedImageUrl,
		arg.Excerpt,
		arg.Date,
	)
	var i PressMention
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.SourceUrl,
		&i.LogoUrl,
		&i.Excerpt,
		&i.Date,
		&i.CreatedAt,
		&i.FeaturedImageUrl,
	)
	return i, err
}
