// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

const addProductCategory = `-- name: AddProductCategory :exec
INSERT INTO "ProductCategory" ("productId", "categoryId") VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddProductCategoryParams struct {
	ProductId  string `json:"productId"`
	CategoryId string `json:"categoryId"`
}

func (q *Queries) AddProductCategory(ctx context.Context, arg AddProductCategoryParams) error {
	_, err := q.db.Exec(ctx, addProductCategory, arg.ProductId, arg.CategoryId)
	return err
}

const addProductTag = `-- name: AddProductTag :exec
INSERT INTO "ProductTag" ("productId", "tagId") VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddProductTagParams struct {
	ProductId string `json:"productId"`
	TagId     string `json:"tagId"`
}

func (q *Queries) AddProductTag(ctx context.Context, arg AddProductTagParams) error {
	_, err := q.db.Exec(ctx, addProductTag, arg.ProductId, arg.TagId)
	return err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO "Product" ("id", "slug", "sku", "price", "compareAtPrice", "stock", "status", "featuredImageUrl", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
RETURNING id, slug, sku, price, "compareAtPrice", stock, "manageStock", status, "wcId", "createdAt", "updatedAt", "featuredImageUrl"
`

type CreateProductParams struct {
	ID               string              `json:"id"`
	Slug             string              `json:"slug"`
	Sku              *string             `json:"sku"`
	Price            decimal.Decimal     `json:"price"`
	CompareAtPrice   decimal.NullDecimal `json:"compareAtPrice"`
	Stock            int32               `json:"stock"`
	Status           ProductStatus       `json:"status"`
	FeaturedImageUrl *string             `json:"featuredImageUrl"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Slug,
		arg.Sku,
		arg.Price,
		arg.CompareAtPrice,
		arg.Stock,
		arg.Status,
		arg.FeaturedImageUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Sku,
		&i.Price,
		&i.CompareAtPrice,
		&i.Stock,
		&i.ManageStock,
		&i.Status,
		&i.WcId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeaturedImageUrl,
	)
	return i, err
}

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO "ProductVariant" ("id", "productId", "sku", "price", "stock", "options")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, "productId", sku, price, stock, options, "wcId"
`

type CreateProductVariantParams struct {
	ID        string          `json:"id"`
	ProductId string          `json:"productId"`
	Sku       *string         `json:"sku"`
	Price     decimal.Decimal `json:"price"`
	Stock     int32           `json:"stock"`
	Options   []byte          `json:"options"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createProductVariant,
		arg.ID,
		arg.ProductId,
		arg.Sku,
		arg.Price,
		arg.Stock,
		arg.Options,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductId,
		&i.Sku,
		&i.Price,
		&i.Stock,
		&i.Options,
		&i.WcId,
	)
	return i, err
}

const decrementStock = `-- name: DecrementStock :execrows
UPDATE "Product" SET "stock" = "stock" - $2, "updatedAt" = NOW()
WHERE "id" = $1 AND "stock" >= $2
`

type DecrementStockParams struct {
	ID    string `json:"id"`
	Stock int32  `json:"stock"`
}

func (q *Queries) DecrementStock(ctx context.Context, arg DecrementStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, decrementStock, arg.ID, arg.Stock)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM "Product" WHERE "id" = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const deleteProductTranslations = `-- name: DeleteProductTranslations :exec
DELETE FROM "ProductTranslation" WHERE "productId" = $1
`

func (q *Queries) DeleteProductTranslations(ctx context.Context, productid string) error {
	_, err := q.db.Exec(ctx, deleteProductTranslations, productid)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, slug, sku, price, "compareAtPrice", stock, "manageStock", status, "wcId", "createdAt", "updatedAt", "featuredImageUrl" FROM "Product" WHERE "id" = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Sku,
		&i.Price,
		&i.CompareAtPrice,
		&i.Stock,
		&i.ManageStock,
		&i.Status,
		&i.WcId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeaturedImageUrl,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT p.id, p.slug, p.sku, p.price, p."compareAtPrice", p.stock, p."manageStock", p.status, p."wcId", p."createdAt", p."updatedAt", p."featuredImageUrl" FROM "Product" p
JOIN "ProductTranslation" pt ON pt."productId" = p."id"
WHERE pt."slug" = $1 AND pt."locale" = $2
`

type GetProductBySlugParams struct {
	Slug   string `json:"slug"`
	Locale Locale `json:"locale"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, arg GetProductBySlugParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, arg.Slug, arg.Locale)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Sku,
		&i.Price,
		&i.CompareAtPrice,
		&i.Stock,
		&i.ManageStock,
		&i.Status,
		&i.WcId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeaturedImageUrl,
	)
	return i, err
}

const getProductCategories = `-- name: GetProductCategories :many
SELECT c."id", c."slug", ct."name"
FROM "ProductCategory" pc
JOIN "Category" c ON c."id" = pc."categoryId"
LEFT JOIN "CategoryTranslation" ct ON ct."categoryId" = c."id" AND ct."locale" = $2
WHERE pc."productId" = $1
`

type GetProductCategoriesParams struct {
	ProductId string `json:"productId"`
	Locale    Locale `json:"locale"`
}

type GetProductCategoriesRow struct {
	ID   string  `json:"id"`
	Slug string  `json:"slug"`
	Name *string `json:"name"`
}

func (q *Queries) GetProductCategories(ctx context.Context, arg GetProductCategoriesParams) ([]GetProductCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getProductCategories, arg.ProductId, arg.Locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductCategoriesRow{}
	for rows.Next() {
		var i GetProductCategoriesRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductImages = `-- name: GetProductImages :many
SELECT id, "productId", position, "imageUrl" FROM "ProductImage"
WHERE "productId" = $1
ORDER BY "position" ASC
`

func (q *Queries) GetProductImages(ctx context.Context, productid string) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, getProductImages, productid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductId,
			&i.Position,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductTags = `-- name: GetProductTags :many
SELECT t."id", t."slug", tt."name"
FROM "ProductTag" pt
JOIN "Tag" t ON t."id" = pt."tagId"
LEFT JOIN "TagTranslation" tt ON tt."tagId" = t."id" AND tt."locale" = $2
WHERE pt."productId" = $1
`

type GetProductTagsParams struct {
	ProductId string `json:"productId"`
	Locale    Locale `json:"locale"`
}

type GetProductTagsRow struct {
	ID   string  `json:"id"`
	Slug string  `json:"slug"`
	Name *string `json:"name"`
}

func (q *Queries) GetProductTags(ctx context.Context, arg GetProductTagsParams) ([]GetProductTagsRow, error) {
	rows, err := q.db.Query(ctx, getProductTags, arg.ProductId, arg.Locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductTagsRow{}
	for rows.Next() {
		var i GetProductTagsRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductTranslations = `-- name: GetProductTranslations :many
SELECT id, "productId", locale, name, description, "shortDescription", slug, "metaTitle", "metaDescription" FROM "ProductTranslation"
WHERE "productId" = $1
`

func (q *Queries) GetProductTranslations(ctx context.Context, productid string) ([]ProductTranslation, error) {
	rows, err := q.db.Query(ctx, getProductTranslations, productid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductTranslation{}
	for rows.Next() {
		var i ProductTranslation
		if err := rows.Scan(
			&i.ID,
			&i.ProductId,
			&i.Locale,
			&i.Name,
			&i.Description,
			&i.ShortDescription,
			&i.Slug,
			&i.MetaTitle,
			&i.MetaDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductVariants = `-- name: GetProductVariants :many
SELECT id, "productId", sku, price, stock, options, "wcId" FROM "ProductVariant" WHERE "productId" = $1
`

func (q *Queries) GetProductVariants(ctx context.Context, productid string) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, getProductVariants, productid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductId,
			&i.Sku,
			&i.Price,
			&i.Stock,
			&i.Options,
			&i.WcId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.slug, p.sku, p.price, p."compareAtPrice", p.stock, p."manageStock", p.status, p."wcId", p."createdAt", p."updatedAt", p."featuredImageUrl", COUNT(*) OVER() AS total_count
FROM "Product" p
WHERE p."status" = COALESCE($1::"ProductStatus", 'PUBLISHED'::"ProductStatus")
  AND (COALESCE($2::numeric, 0) = 0 OR p."price" >= $2::numeric)
  AND (COALESCE($3::numeric, 0) = 0 OR p."price" <= $3::numeric)
  AND ($4::text IS NULL OR EXISTS (
      SELECT 1 FROM "ProductCategory" pc
      JOIN "Category" c ON c."id" = pc."categoryId"
      WHERE pc."productId" = p."id" AND c."slug" = $4::text
  ))
  AND ($5::text IS NULL OR EXISTS (
      SELECT 1 FROM "ProductTag" pt
      JOIN "Tag" t ON t."id" = pt."tagId"
      WHERE pt."productId" = p."id" AND t."slug" = $5::text
  ))
  AND ($6::text IS NULL OR EXISTS (
      SELECT 1 FROM "ProductTranslation" pt
      WHERE pt."productId" = p."id" AND (
          pt."name" ILIKE '%' || $6::text || '%'
          OR pt."description" ILIKE '%' || $6::text || '%'
      )
  ))
ORDER BY
  CASE WHEN $7::text = 'asc' THEN p."createdAt" END ASC,
  CASE WHEN $7::text != 'asc' OR $7 IS NULL THEN p."createdAt" END DESC
LIMIT $9 OFFSET $8
`

type ListProductsParams struct {
	Status       NullProductStatus   `json:"status"`
	MinPrice     decimal.NullDecimal `json:"min_price"`
	MaxPrice     decimal.NullDecimal `json:"max_price"`
	CategorySlug *string             `json:"category_slug"`
	TagSlug      *string             `json:"tag_slug"`
	Search       *string             `json:"search"`
	OrderBy      *string             `json:"order_by"`
	Offset       int32               `json:"offset"`
	Limit        int32               `json:"limit"`
}

type ListProductsRow struct {
	ID               string              `json:"id"`
	Slug             string              `json:"slug"`
	Sku              *string             `json:"sku"`
	Price            decimal.Decimal     `json:"price"`
	CompareAtPrice   decimal.NullDecimal `json:"compareAtPrice"`
	Stock            int32               `json:"stock"`
	ManageStock      bool                `json:"manageStock"`
	Status           ProductStatus       `json:"status"`
	WcId             *int32              `json:"wcId"`
	CreatedAt        pgtype.Timestamp    `json:"createdAt"`
	UpdatedAt        pgtype.Timestamp    `json:"updatedAt"`
	FeaturedImageUrl *string             `json:"featuredImageUrl"`
	TotalCount       int64               `json:"total_count"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Status,
		arg.MinPrice,
		arg.MaxPrice,
		arg.CategorySlug,
		arg.TagSlug,
		arg.Search,
		arg.OrderBy,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Sku,
			&i.Price,
			&i.CompareAtPrice,
			&i.Stock,
			&i.ManageStock,
			&i.Status,
			&i.WcId,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeaturedImageUrl,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE "Product"
SET "sku" = COALESCE($2, "sku"),
    "price" = COALESCE($3::numeric, "price"),
    "compareAtPrice" = $4::numeric,
    "stock" = COALESCE($5::int, "stock"),
    "status" = COALESCE($6::"ProductStatus", "status"),
    "featuredImageUrl" = COALESCE($7, "featuredImageUrl"),
    "updatedAt" = NOW()
WHERE "id" = $1
RETURNING id, slug, sku, price, "compareAtPrice", stock, "manageStock", status, "wcId", "createdAt", "updatedAt", "featuredImageUrl"
`

type UpdateProductParams struct {
	ID               string              `json:"id"`
	Sku              *string             `json:"sku"`
	Price            decimal.NullDecimal `json:"price"`
	CompareAtPrice   decimal.NullDecimal `json:"compare_at_price"`
	Stock            *int32              `json:"stock"`
	Status           NullProductStatus   `json:"status"`
	FeaturedImageUrl *string             `json:"featured_image_url"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Sku,
		arg.Price,
		arg.CompareAtPrice,
		arg.Stock,
		arg.Status,
		arg.FeaturedImageUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Sku,
		&i.Price,
		&i.CompareAtPrice,
		&i.Stock,
		&i.ManageStock,
		&i.Status,
		&i.WcId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeaturedImageUrl,
	)
	return i, err
}

const upsertProductTranslation = `-- name: UpsertProductTranslation :one
INSERT INTO "ProductTranslation" ("id", "productId", "locale", "name", "slug", "description", "shortDescription", "metaTitle", "metaDescription")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT ("productId", "locale") DO UPDATE
  SET "name" = EXCLUDED."name", "slug" = EXCLUDED."slug",
      "description" = EXCLUDED."description", "shortDescription" = EXCLUDED."shortDescription",
      "metaTitle" = EXCLUDED."metaTitle", "metaDescription" = EXCLUDED."metaDescription"
RETURNING id, "productId", locale, name, description, "shortDescription", slug, "metaTitle", "metaDescription"
`

type UpsertProductTranslationParams struct {
	ID               string  `json:"id"`
	ProductId        string  `json:"productId"`
	Locale           Locale  `json:"locale"`
	Name             string  `json:"name"`
	Slug             string  `json:"slug"`
	Description      *string `json:"description"`
	ShortDescription *string `json:"shortDescription"`
	MetaTitle        *string `json:"metaTitle"`
	MetaDescription  *string `json:"metaDescription"`
}

func (q *Queries) UpsertProductTranslation(ctx context.Context, arg UpsertProductTranslationParams) (ProductTranslation, error) {
	row := q.db.QueryRow(ctx, upsertProductTranslation,
		arg.ID,
		arg.ProductId,
		arg.Locale,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ShortDescription,
		arg.MetaTitle,
		arg.MetaDescription,
	)
	var i ProductTranslation
	err := row.Scan(
		&i.ID,
		&i.ProductId,
		&i.Locale,
		&i.Name,
		&i.Description,
		&i.ShortDescription,
		&i.Slug,
		&i.MetaTitle,
		&i.MetaDescription,
	)
	return i, err
}
