// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO "Project" ("id", "slug", "featuredImageUrl", "gallery", "completedAt", "clientName", "country", "status", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
RETURNING id, slug, "completedAt", "clientName", country, status, "createdAt", "updatedAt", "featuredImageUrl", gallery
`

type CreateProjectParams struct {
	ID               string           `json:"id"`
	Slug             string           `json:"slug"`
	FeaturedImageUrl *string          `json:"featuredImageUrl"`
	Gallery          []byte           `json:"gallery"`
	CompletedAt      pgtype.Timestamp `json:"completedAt"`
	ClientName       *string          `json:"clientName"`
	Country          *string          `json:"country"`
	Status           ProductStatus    `json:"status"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.Slug,
		arg.FeaturedImageUrl,
		arg.Gallery,
		arg.CompletedAt,
		arg.ClientName,
		arg.Country,
		arg.Status,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.CompletedAt,
		&i.ClientName,
		&i.Country,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeaturedImageUrl,
		&i.Gallery,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM "Project" WHERE "id" = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, slug, "completedAt", "clientName", country, status, "createdAt", "updatedAt", "featuredImageUrl", gallery FROM "Project" WHERE "id" = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.CompletedAt,
		&i.ClientName,
		&i.Country,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeaturedImageUrl,
		&i.Gallery,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, slug, "completedAt", "clientName", country, status, "createdAt", "updatedAt", "featuredImageUrl", gallery FROM "Project" WHERE "slug" = $1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.CompletedAt,
		&i.ClientName,
		&i.Country,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeaturedImageUrl,
		&i.Gallery,
	)
	return i, err
}

const getProjectTranslations = `-- name: GetProjectTranslations :many
SELECT id, "projectId", locale, title, summary, content, "metaTitle", "metaDescription" FROM "ProjectTranslation" WHERE "projectId" = $1
`

func (q *Queries) GetProjectTranslations(ctx context.Context, projectid string) ([]ProjectTranslation, error) {
	rows, err := q.db.Query(ctx, getProjectTranslations, projectid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectTranslation{}
	for rows.Next() {
		var i ProjectTranslation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectId,
			&i.Locale,
			&i.Title,
			&i.Summary,
			&i.Content,
			&i.MetaTitle,
			&i.MetaDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.slug, p."completedAt", p."clientName", p.country, p.status, p."createdAt", p."updatedAt", p."featuredImageUrl", p.gallery, COUNT(*) OVER() AS total_count
FROM "Project" p
WHERE p."status" = 'PUBLISHED'::"ProductStatus"
ORDER BY p."completedAt" DESC NULLS LAST, p."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListProjectsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProjectsRow struct {
	ID               string           `json:"id"`
	Slug             string           `json:"slug"`
	CompletedAt      pgtype.Timestamp `json:"completedAt"`
	ClientName       *string          `json:"clientName"`
	Country          *string          `json:"country"`
	Status           ProductStatus    `json:"status"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	UpdatedAt        pgtype.Timestamp `json:"updatedAt"`
	FeaturedImageUrl *string          `json:"featuredImageUrl"`
	Gallery          []byte           `json:"gallery"`
	TotalCount       int64            `json:"total_count"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.CompletedAt,
			&i.ClientName,
			&i.Country,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeaturedImageUrl,
			&i.Gallery,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE "Project"
SET "featuredImageUrl" = COALESCE($2, "featuredImageUrl"),
    "gallery" = COALESCE($3, "gallery"),
    "completedAt" = $4,
    "clientName" = COALESCE($5, "clientName"),
    "country" = COALESCE($6, "country"),
    "status" = COALESCE($7::"ProductStatus", "status"),
    "updatedAt" = NOW()
WHERE "id" = $1
RETURNING id, slug, "completedAt", "clientName", country, status, "createdAt", "updatedAt", "featuredImageUrl", gallery
`

type UpdateProjectParams struct {
	ID               string            `json:"id"`
	FeaturedImageUrl *string           `json:"featured_image_url"`
	Gallery          []byte            `json:"gallery"`
	CompletedAt      pgtype.Timestamp  `json:"completed_at"`
	ClientName       *string           `json:"client_name"`
	Country          *string           `json:"country"`
	Status           NullProductStatus `json:"status"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.FeaturedImageUrl,
		arg.Gallery,
		arg.CompletedAt,
		arg.ClientName,
		arg.Country,
		arg.Status,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.CompletedAt,
		&i.ClientName,
		&i.Country,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeaturedImageUrl,
		&i.Gallery,
	)
	return i, err
}

const upsertProjectTranslation = `-- name: UpsertProjectTranslation :one
INSERT INTO "ProjectTranslation" ("id", "projectId", "locale", "title", "summary", "content", "metaTitle", "metaDescription")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT ("projectId", "locale") DO UPDATE
  SET "title" = EXCLUDED."title", "summary" = EXCLUDED."summary",
      "content" = EXCLUDED."content", "metaTitle" = EXCLUDED."metaTitle",
      "metaDescription" = EXCLUDED."metaDescription"
RETURNING id, "projectId", locale, title, summary, content, "metaTitle", "metaDescription"
`

type UpsertProjectTranslationParams struct {
	ID              string  `json:"id"`
	ProjectId       string  `json:"projectId"`
	Locale          Locale  `json:"locale"`
	Title           string  `json:"title"`
	Summary         *string `json:"summary"`
	Content         *string `json:"content"`
	MetaTitle       *string `json:"metaTitle"`
	MetaDescription *string `json:"metaDescription"`
}

func (q *Queries) UpsertProjectTranslation(ctx context.Context, arg UpsertProjectTranslationParams) (ProjectTranslation, error) {
	row := q.db.QueryRow(ctx, upsertProjectTranslation,
		arg.ID,
		arg.ProjectId,
		arg.Locale,
		arg.Title,
		arg.Summary,
		arg.Content,
		arg.MetaTitle,
		arg.MetaDescription,
	)
	var i ProjectTranslation
	err := row.Scan(
		&i.ID,
		&i.ProjectId,
		&i.Locale,
		&i.Title,
		&i.Summary,
		&i.Content,
		&i.MetaTitle,
		&i.MetaDescription,
	)
	return i, err
}
