// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quotes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuote = `-- name: CreateQuote :one
INSERT INTO "Quote" ("id", "name", "surname", "email", "phone", "company", "orderType", "quantity", "deliveryDate", "message", "status", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'NEW', NOW(), NOW())
RETURNING id, name, surname, email, phone, company, "orderType", quantity, "deliveryDate", message, status, "createdAt", "updatedAt"
`

type CreateQuoteParams struct {
	ID           string           `json:"id"`
	Name         string           `json:"name"`
	Surname      *string          `json:"surname"`
	Email        string           `json:"email"`
	Phone        *string          `json:"phone"`
	Company      *string          `json:"company"`
	OrderType    string           `json:"orderType"`
	Quantity     *int32           `json:"quantity"`
	DeliveryDate pgtype.Timestamp `json:"deliveryDate"`
	Message      string           `json:"message"`
}

func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, createQuote,
		arg.ID,
		arg.Name,
		arg.Surname,
		arg.Email,
		arg.Phone,
		arg.Company,
		arg.OrderType,
		arg.Quantity,
		arg.DeliveryDate,
		arg.Message,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Phone,
		&i.Company,
		&i.OrderType,
		&i.Quantity,
		&i.DeliveryDate,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuoteByID = `-- name: GetQuoteByID :one
SELECT id, name, surname, email, phone, company, "orderType", quantity, "deliveryDate", message, status, "createdAt", "updatedAt" FROM "Quote" WHERE "id" = $1
`

func (q *Queries) GetQuoteByID(ctx context.Context, id string) (Quote, error) {
	row := q.db.QueryRow(ctx, getQuoteByID, id)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Phone,
		&i.Company,
		&i.OrderType,
		&i.Quantity,
		&i.DeliveryDate,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuotes = `-- name: ListQuotes :many
SELECT id, name, surname, email, phone, company, "orderType", quantity, "deliveryDate", message, status, "createdAt", "updatedAt", COUNT(*) OVER() AS total_count
FROM "Quote"
ORDER BY "createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListQuotesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListQuotesRow struct {
	ID           string           `json:"id"`
	Name         string           `json:"name"`
	Surname      *string          `json:"surname"`
	Email        string           `json:"email"`
	Phone        *string          `json:"phone"`
	Company      *string          `json:"company"`
	OrderType    string           `json:"orderType"`
	Quantity     *int32           `json:"quantity"`
	DeliveryDate pgtype.Timestamp `json:"deliveryDate"`
	Message      string           `json:"message"`
	Status       string           `json:"status"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
	TotalCount   int64            `json:"total_count"`
}

func (q *Queries) ListQuotes(ctx context.Context, arg ListQuotesParams) ([]ListQuotesRow, error) {
	rows, err := q.db.Query(ctx, listQuotes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuotesRow{}
	for rows.Next() {
		var i ListQuotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.Email,
			&i.Phone,
			&i.Company,
			&i.OrderType,
			&i.Quantity,
			&i.DeliveryDate,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuoteStatus = `-- name: UpdateQuoteStatus :one
UPDATE "Quote" SET "status" = $2, "updatedAt" = NOW()
WHERE "id" = $1
RETURNING id, name, surname, email, phone, company, "orderType", quantity, "deliveryDate", message, status, "createdAt", "updatedAt"
`

type UpdateQuoteStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateQuoteStatus(ctx context.Context, arg UpdateQuoteStatusParams) (Quote, error) {
	row := q.db.QueryRow(ctx, updateQuoteStatus, arg.ID, arg.Status)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Phone,
		&i.Company,
		&i.OrderType,
		&i.Quantity,
		&i.DeliveryDate,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
