// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refunds.sql

package db

import (
	"context"

	decimal "github.com/shopspring/decimal"
)

const createRefundRequest = `-- name: CreateRefundRequest :one
INSERT INTO "RefundRequest" (
    "id", "orderId", "paymentId", "amount", "currency", "reason",
    "status", "idempotencyKey", "requestedBy", "requestedAt"
) VALUES (
    $1, $2, $3, $4, $5, $6,
    'PENDING'::"RefundStatus", $7, $8, NOW()
)
RETURNING id, "orderId", "paymentId", amount, currency, reason, status, "providerRefundId", "idempotencyKey", "requestedBy", "requestedAt", "completedAt", "errorMessage", "manualReference", "justificationUrl"
`

type CreateRefundRequestParams struct {
	ID             string          `json:"id"`
	OrderId        string          `json:"orderId"`
	PaymentId      string          `json:"paymentId"`
	Amount         decimal.Decimal `json:"amount"`
	Currency       string          `json:"currency"`
	Reason         string          `json:"reason"`
	IdempotencyKey string          `json:"idempotencyKey"`
	RequestedBy    string          `json:"requestedBy"`
}

func (q *Queries) CreateRefundRequest(ctx context.Context, arg CreateRefundRequestParams) (RefundRequest, error) {
	row := q.db.QueryRow(ctx, createRefundRequest,
		arg.ID,
		arg.OrderId,
		arg.PaymentId,
		arg.Amount,
		arg.Currency,
		arg.Reason,
		arg.IdempotencyKey,
		arg.RequestedBy,
	)
	var i RefundRequest
	err := row.Scan(
		&i.ID,
		&i.OrderId,
		&i.PaymentId,
		&i.Amount,
		&i.Currency,
		&i.Reason,
		&i.Status,
		&i.ProviderRefundId,
		&i.IdempotencyKey,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.ManualReference,
		&i.JustificationUrl,
	)
	return i, err
}

const getRefundRequestByID = `-- name: GetRefundRequestByID :one
SELECT id, "orderId", "paymentId", amount, currency, reason, status, "providerRefundId", "idempotencyKey", "requestedBy", "requestedAt", "completedAt", "errorMessage", "manualReference", "justificationUrl" FROM "RefundRequest" WHERE "id" = $1
`

func (q *Queries) GetRefundRequestByID(ctx context.Context, id string) (RefundRequest, error) {
	row := q.db.QueryRow(ctx, getRefundRequestByID, id)
	var i RefundRequest
	err := row.Scan(
		&i.ID,
		&i.OrderId,
		&i.PaymentId,
		&i.Amount,
		&i.Currency,
		&i.Reason,
		&i.Status,
		&i.ProviderRefundId,
		&i.IdempotencyKey,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.ManualReference,
		&i.JustificationUrl,
	)
	return i, err
}

const getRefundRequestByIdempotencyKey = `-- name: GetRefundRequestByIdempotencyKey :one
SELECT id, "orderId", "paymentId", amount, currency, reason, status, "providerRefundId", "idempotencyKey", "requestedBy", "requestedAt", "completedAt", "errorMessage", "manualReference", "justificationUrl" FROM "RefundRequest" WHERE "idempotencyKey" = $1
`

func (q *Queries) GetRefundRequestByIdempotencyKey(ctx context.Context, idempotencykey string) (RefundRequest, error) {
	row := q.db.QueryRow(ctx, getRefundRequestByIdempotencyKey, idempotencykey)
	var i RefundRequest
	err := row.Scan(
		&i.ID,
		&i.OrderId,
		&i.PaymentId,
		&i.Amount,
		&i.Currency,
		&i.Reason,
		&i.Status,
		&i.ProviderRefundId,
		&i.IdempotencyKey,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.ManualReference,
		&i.JustificationUrl,
	)
	return i, err
}

const listRefundsByOrderID = `-- name: ListRefundsByOrderID :many
SELECT id, "orderId", "paymentId", amount, currency, reason, status, "providerRefundId", "idempotencyKey", "requestedBy", "requestedAt", "completedAt", "errorMessage", "manualReference", "justificationUrl" FROM "RefundRequest" WHERE "orderId" = $1 ORDER BY "requestedAt" DESC
`

func (q *Queries) ListRefundsByOrderID(ctx context.Context, orderid string) ([]RefundRequest, error) {
	rows, err := q.db.Query(ctx, listRefundsByOrderID, orderid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefundRequest{}
	for rows.Next() {
		var i RefundRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrderId,
			&i.PaymentId,
			&i.Amount,
			&i.Currency,
			&i.Reason,
			&i.Status,
			&i.ProviderRefundId,
			&i.IdempotencyKey,
			&i.RequestedBy,
			&i.RequestedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.ManualReference,
			&i.JustificationUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRefundManualCompleted = `-- name: MarkRefundManualCompleted :one
UPDATE "RefundRequest"
SET "status"          = 'SUCCEEDED'::"RefundStatus",
    "manualReference" = $2,
    "justificationUrl"= $3,
    "completedAt"     = NOW()
WHERE "id" = $1
RETURNING id, "orderId", "paymentId", amount, currency, reason, status, "providerRefundId", "idempotencyKey", "requestedBy", "requestedAt", "completedAt", "errorMessage", "manualReference", "justificationUrl"
`

type MarkRefundManualCompletedParams struct {
	ID               string  `json:"id"`
	ManualReference  *string `json:"manualReference"`
	JustificationUrl *string `json:"justificationUrl"`
}

func (q *Queries) MarkRefundManualCompleted(ctx context.Context, arg MarkRefundManualCompletedParams) (RefundRequest, error) {
	row := q.db.QueryRow(ctx, markRefundManualCompleted, arg.ID, arg.ManualReference, arg.JustificationUrl)
	var i RefundRequest
	err := row.Scan(
		&i.ID,
		&i.OrderId,
		&i.PaymentId,
		&i.Amount,
		&i.Currency,
		&i.Reason,
		&i.Status,
		&i.ProviderRefundId,
		&i.IdempotencyKey,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.ManualReference,
		&i.JustificationUrl,
	)
	return i, err
}

const sumRefundsByOrderID = `-- name: SumRefundsByOrderID :one
SELECT COALESCE(SUM("amount"), 0)::DECIMAL(10,2) AS total
FROM "RefundRequest"
WHERE "orderId" = $1
  AND "status" IN ('PENDING','SUCCEEDED')
`

// Sum of PENDING + SUCCEEDED refunds for cap check.
func (q *Queries) SumRefundsByOrderID(ctx context.Context, orderid string) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, sumRefundsByOrderID, orderid)
	var total decimal.Decimal
	err := row.Scan(&total)
	return total, err
}

const updateRefundStatus = `-- name: UpdateRefundStatus :one
UPDATE "RefundRequest"
SET "status" = $2::"RefundStatus",
    "providerRefundId" = COALESCE($3::text, "providerRefundId"),
    "errorMessage"     = COALESCE($4::text, "errorMessage"),
    "completedAt"      = CASE WHEN $2::text IN ('SUCCEEDED','FAILED','CANCELLED') THEN NOW() ELSE "completedAt" END
WHERE "id" = $1
RETURNING id, "orderId", "paymentId", amount, currency, reason, status, "providerRefundId", "idempotencyKey", "requestedBy", "requestedAt", "completedAt", "errorMessage", "manualReference", "justificationUrl"
`

type UpdateRefundStatusParams struct {
	ID               string       `json:"id"`
	Status           RefundStatus `json:"status"`
	ProviderRefundId *string      `json:"providerRefundId"`
	ErrorMessage     *string      `json:"errorMessage"`
}

func (q *Queries) UpdateRefundStatus(ctx context.Context, arg UpdateRefundStatusParams) (RefundRequest, error) {
	row := q.db.QueryRow(ctx, updateRefundStatus,
		arg.ID,
		arg.Status,
		arg.ProviderRefundId,
		arg.ErrorMessage,
	)
	var i RefundRequest
	err := row.Scan(
		&i.ID,
		&i.OrderId,
		&i.PaymentId,
		&i.Amount,
		&i.Currency,
		&i.Reason,
		&i.Status,
		&i.ProviderRefundId,
		&i.IdempotencyKey,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.ManualReference,
		&i.JustificationUrl,
	)
	return i, err
}
