// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO "Service" ("id", "slug", "icon", "status", "menuOrder", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, slug, icon, status, "menuOrder", "createdAt", "updatedAt"
`

type CreateServiceParams struct {
	ID        string        `json:"id"`
	Slug      string        `json:"slug"`
	Icon      *string       `json:"icon"`
	Status    ProductStatus `json:"status"`
	MenuOrder int32         `json:"menuOrder"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.ID,
		arg.Slug,
		arg.Icon,
		arg.Status,
		arg.MenuOrder,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Icon,
		&i.Status,
		&i.MenuOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM "Service" WHERE "id" = $1
`

func (q *Queries) DeleteService(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, slug, icon, status, "menuOrder", "createdAt", "updatedAt" FROM "Service" WHERE "id" = $1
`

func (q *Queries) GetServiceByID(ctx context.Context, id string) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Icon,
		&i.Status,
		&i.MenuOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceBySlug = `-- name: GetServiceBySlug :one
SELECT id, slug, icon, status, "menuOrder", "createdAt", "updatedAt" FROM "Service" WHERE "slug" = $1
`

func (q *Queries) GetServiceBySlug(ctx context.Context, slug string) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceBySlug, slug)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Icon,
		&i.Status,
		&i.MenuOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceTranslations = `-- name: GetServiceTranslations :many
SELECT id, "serviceId", locale, title, description, "metaTitle", "metaDescription" FROM "ServiceTranslation" WHERE "serviceId" = $1
`

func (q *Queries) GetServiceTranslations(ctx context.Context, serviceid string) ([]ServiceTranslation, error) {
	rows, err := q.db.Query(ctx, getServiceTranslations, serviceid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceTranslation{}
	for rows.Next() {
		var i ServiceTranslation
		if err := rows.Scan(
			&i.ID,
			&i.ServiceId,
			&i.Locale,
			&i.Title,
			&i.Description,
			&i.MetaTitle,
			&i.MetaDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT s.id, s.slug, s.icon, s.status, s."menuOrder", s."createdAt", s."updatedAt", COUNT(*) OVER() AS total_count
FROM "Service" s
WHERE s."status" = 'PUBLISHED'::"ProductStatus"
ORDER BY s."menuOrder" ASC, s."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListServicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListServicesRow struct {
	ID         string           `json:"id"`
	Slug       string           `json:"slug"`
	Icon       *string          `json:"icon"`
	Status     ProductStatus    `json:"status"`
	MenuOrder  int32            `json:"menuOrder"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
	TotalCount int64            `json:"total_count"`
}

func (q *Queries) ListServices(ctx context.Context, arg ListServicesParams) ([]ListServicesRow, error) {
	rows, err := q.db.Query(ctx, listServices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesRow{}
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Icon,
			&i.Status,
			&i.MenuOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE "Service"
SET "icon" = COALESCE($2, "icon"),
    "status" = COALESCE($3::"ProductStatus", "status"),
    "menuOrder" = COALESCE($4::int, "menuOrder"),
    "updatedAt" = NOW()
WHERE "id" = $1
RETURNING id, slug, icon, status, "menuOrder", "createdAt", "updatedAt"
`

type UpdateServiceParams struct {
	ID        string         `json:"id"`
	Icon      *string        `json:"icon"`
	Status    *ProductStatus `json:"status"`
	MenuOrder *int32         `json:"menu_order"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Icon,
		arg.Status,
		arg.MenuOrder,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Icon,
		&i.Status,
		&i.MenuOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertServiceTranslation = `-- name: UpsertServiceTranslation :one
INSERT INTO "ServiceTranslation" ("id", "serviceId", "locale", "title", "description", "metaTitle", "metaDescription")
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT ("serviceId", "locale") DO UPDATE
  SET "title" = EXCLUDED."title", "description" = EXCLUDED."description",
      "metaTitle" = EXCLUDED."metaTitle", "metaDescription" = EXCLUDED."metaDescription"
RETURNING id, "serviceId", locale, title, description, "metaTitle", "metaDescription"
`

type UpsertServiceTranslationParams struct {
	ID              string  `json:"id"`
	ServiceId       string  `json:"serviceId"`
	Locale          Locale  `json:"locale"`
	Title           string  `json:"title"`
	Description     string  `json:"description"`
	MetaTitle       *string `json:"metaTitle"`
	MetaDescription *string `json:"metaDescription"`
}

func (q *Queries) UpsertServiceTranslation(ctx context.Context, arg UpsertServiceTranslationParams) (ServiceTranslation, error) {
	row := q.db.QueryRow(ctx, upsertServiceTranslation,
		arg.ID,
		arg.ServiceId,
		arg.Locale,
		arg.Title,
		arg.Description,
		arg.MetaTitle,
		arg.MetaDescription,
	)
	var i ServiceTranslation
	err := row.Scan(
		&i.ID,
		&i.ServiceId,
		&i.Locale,
		&i.Title,
		&i.Description,
		&i.MetaTitle,
		&i.MetaDescription,
	)
	return i, err
}
