// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shipping.sql

package db

import (
	"context"

	decimal "github.com/shopspring/decimal"
)

const createShippingMethod = `-- name: CreateShippingMethod :one
INSERT INTO "ShippingMethod" ("id", "code", "isPickup", "enabled", "estimatedDaysMin", "estimatedDaysMax", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
RETURNING id, code, "isPickup", enabled, "estimatedDaysMin", "estimatedDaysMax", "createdAt", "updatedAt"
`

type CreateShippingMethodParams struct {
	ID               string `json:"id"`
	Code             string `json:"code"`
	IsPickup         bool   `json:"isPickup"`
	Enabled          bool   `json:"enabled"`
	EstimatedDaysMin *int32 `json:"estimatedDaysMin"`
	EstimatedDaysMax *int32 `json:"estimatedDaysMax"`
}

func (q *Queries) CreateShippingMethod(ctx context.Context, arg CreateShippingMethodParams) (ShippingMethod, error) {
	row := q.db.QueryRow(ctx, createShippingMethod,
		arg.ID,
		arg.Code,
		arg.IsPickup,
		arg.Enabled,
		arg.EstimatedDaysMin,
		arg.EstimatedDaysMax,
	)
	var i ShippingMethod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.IsPickup,
		&i.Enabled,
		&i.EstimatedDaysMin,
		&i.EstimatedDaysMax,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createShippingZone = `-- name: CreateShippingZone :one
INSERT INTO "ShippingZone" ("id", "code", "isDefault", "priority", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, code, "isDefault", priority, "createdAt", "updatedAt"
`

type CreateShippingZoneParams struct {
	ID        string `json:"id"`
	Code      string `json:"code"`
	IsDefault bool   `json:"isDefault"`
	Priority  int32  `json:"priority"`
}

func (q *Queries) CreateShippingZone(ctx context.Context, arg CreateShippingZoneParams) (ShippingZone, error) {
	row := q.db.QueryRow(ctx, createShippingZone,
		arg.ID,
		arg.Code,
		arg.IsDefault,
		arg.Priority,
	)
	var i ShippingZone
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.IsDefault,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createShippingZoneRule = `-- name: CreateShippingZoneRule :one
INSERT INTO "ShippingZoneRule" ("id", "zoneId", "country", "region", "postalCodePattern")
VALUES ($1, $2, $3, $4, $5)
RETURNING id, "zoneId", country, region, "postalCodePattern"
`

type CreateShippingZoneRuleParams struct {
	ID                string  `json:"id"`
	ZoneId            string  `json:"zoneId"`
	Country           string  `json:"country"`
	Region            *string `json:"region"`
	PostalCodePattern *string `json:"postalCodePattern"`
}

func (q *Queries) CreateShippingZoneRule(ctx context.Context, arg CreateShippingZoneRuleParams) (ShippingZoneRule, error) {
	row := q.db.QueryRow(ctx, createShippingZoneRule,
		arg.ID,
		arg.ZoneId,
		arg.Country,
		arg.Region,
		arg.PostalCodePattern,
	)
	var i ShippingZoneRule
	err := row.Scan(
		&i.ID,
		&i.ZoneId,
		&i.Country,
		&i.Region,
		&i.PostalCodePattern,
	)
	return i, err
}

const deleteShippingMethod = `-- name: DeleteShippingMethod :exec
DELETE FROM "ShippingMethod" WHERE "id" = $1
`

func (q *Queries) DeleteShippingMethod(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteShippingMethod, id)
	return err
}

const deleteShippingZone = `-- name: DeleteShippingZone :exec
DELETE FROM "ShippingZone" WHERE "id" = $1
`

func (q *Queries) DeleteShippingZone(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteShippingZone, id)
	return err
}

const deleteShippingZoneRule = `-- name: DeleteShippingZoneRule :exec
DELETE FROM "ShippingZoneRule" WHERE "id" = $1
`

func (q *Queries) DeleteShippingZoneRule(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteShippingZoneRule, id)
	return err
}

const getDefaultShippingRates = `-- name: GetDefaultShippingRates :many
SELECT sr.id, sr."zoneId", sr."methodId", sr."flatFee", sr."freeAbove", sr.currency
FROM "ShippingRate" sr
JOIN "ShippingMethod" sm ON sm."id" = sr."methodId"
JOIN "ShippingZone" sz ON sz."id" = sr."zoneId"
WHERE sm."enabled" = true
  AND sz."isDefault" = true
ORDER BY sm."code" ASC
`

// Returns all enabled ShippingRates for the default zone (fallback).
func (q *Queries) GetDefaultShippingRates(ctx context.Context) ([]ShippingRate, error) {
	rows, err := q.db.Query(ctx, getDefaultShippingRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShippingRate{}
	for rows.Next() {
		var i ShippingRate
		if err := rows.Scan(
			&i.ID,
			&i.ZoneId,
			&i.MethodId,
			&i.FlatFee,
			&i.FreeAbove,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShippingMethodByID = `-- name: GetShippingMethodByID :one
SELECT id, code, "isPickup", enabled, "estimatedDaysMin", "estimatedDaysMax", "createdAt", "updatedAt" FROM "ShippingMethod" WHERE "id" = $1
`

func (q *Queries) GetShippingMethodByID(ctx context.Context, id string) (ShippingMethod, error) {
	row := q.db.QueryRow(ctx, getShippingMethodByID, id)
	var i ShippingMethod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.IsPickup,
		&i.Enabled,
		&i.EstimatedDaysMin,
		&i.EstimatedDaysMax,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShippingRatesForCountry = `-- name: GetShippingRatesForCountry :many
SELECT sr.id, sr."zoneId", sr."methodId", sr."flatFee", sr."freeAbove", sr.currency
FROM "ShippingRate" sr
JOIN "ShippingMethod" sm ON sm."id" = sr."methodId"
JOIN "ShippingZone" sz ON sz."id" = sr."zoneId"
JOIN "ShippingZoneRule" szr ON szr."zoneId" = sz."id"
WHERE sm."enabled" = true
  AND szr."country" = $1
ORDER BY sz."priority" ASC, sm."code" ASC
`

// Returns all enabled ShippingRates for zones matching the given country.
func (q *Queries) GetShippingRatesForCountry(ctx context.Context, country string) ([]ShippingRate, error) {
	rows, err := q.db.Query(ctx, getShippingRatesForCountry, country)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShippingRate{}
	for rows.Next() {
		var i ShippingRate
		if err := rows.Scan(
			&i.ID,
			&i.ZoneId,
			&i.MethodId,
			&i.FlatFee,
			&i.FreeAbove,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShippingZoneByID = `-- name: GetShippingZoneByID :one
SELECT id, code, "isDefault", priority, "createdAt", "updatedAt" FROM "ShippingZone" WHERE "id" = $1
`

func (q *Queries) GetShippingZoneByID(ctx context.Context, id string) (ShippingZone, error) {
	row := q.db.QueryRow(ctx, getShippingZoneByID, id)
	var i ShippingZone
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.IsDefault,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listShippingMethodTranslations = `-- name: ListShippingMethodTranslations :many
SELECT id, "methodId", locale, name, description FROM "ShippingMethodTranslation" WHERE "methodId" = $1
`

func (q *Queries) ListShippingMethodTranslations(ctx context.Context, methodid string) ([]ShippingMethodTranslation, error) {
	rows, err := q.db.Query(ctx, listShippingMethodTranslations, methodid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShippingMethodTranslation{}
	for rows.Next() {
		var i ShippingMethodTranslation
		if err := rows.Scan(
			&i.ID,
			&i.MethodId,
			&i.Locale,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippingMethods = `-- name: ListShippingMethods :many
SELECT id, code, "isPickup", enabled, "estimatedDaysMin", "estimatedDaysMax", "createdAt", "updatedAt" FROM "ShippingMethod" ORDER BY "code" ASC
`

func (q *Queries) ListShippingMethods(ctx context.Context) ([]ShippingMethod, error) {
	rows, err := q.db.Query(ctx, listShippingMethods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShippingMethod{}
	for rows.Next() {
		var i ShippingMethod
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.IsPickup,
			&i.Enabled,
			&i.EstimatedDaysMin,
			&i.EstimatedDaysMax,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippingRates = `-- name: ListShippingRates :many
SELECT id, "zoneId", "methodId", "flatFee", "freeAbove", currency FROM "ShippingRate" WHERE "zoneId" = $1
`

func (q *Queries) ListShippingRates(ctx context.Context, zoneid string) ([]ShippingRate, error) {
	rows, err := q.db.Query(ctx, listShippingRates, zoneid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShippingRate{}
	for rows.Next() {
		var i ShippingRate
		if err := rows.Scan(
			&i.ID,
			&i.ZoneId,
			&i.MethodId,
			&i.FlatFee,
			&i.FreeAbove,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippingZoneRules = `-- name: ListShippingZoneRules :many
SELECT id, "zoneId", country, region, "postalCodePattern" FROM "ShippingZoneRule" WHERE "zoneId" = $1
`

func (q *Queries) ListShippingZoneRules(ctx context.Context, zoneid string) ([]ShippingZoneRule, error) {
	rows, err := q.db.Query(ctx, listShippingZoneRules, zoneid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShippingZoneRule{}
	for rows.Next() {
		var i ShippingZoneRule
		if err := rows.Scan(
			&i.ID,
			&i.ZoneId,
			&i.Country,
			&i.Region,
			&i.PostalCodePattern,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippingZoneTranslations = `-- name: ListShippingZoneTranslations :many
SELECT id, "zoneId", locale, name FROM "ShippingZoneTranslation" WHERE "zoneId" = $1
`

func (q *Queries) ListShippingZoneTranslations(ctx context.Context, zoneid string) ([]ShippingZoneTranslation, error) {
	rows, err := q.db.Query(ctx, listShippingZoneTranslations, zoneid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShippingZoneTranslation{}
	for rows.Next() {
		var i ShippingZoneTranslation
		if err := rows.Scan(
			&i.ID,
			&i.ZoneId,
			&i.Locale,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippingZones = `-- name: ListShippingZones :many
SELECT id, code, "isDefault", priority, "createdAt", "updatedAt" FROM "ShippingZone" ORDER BY "priority" ASC, "code" ASC
`

func (q *Queries) ListShippingZones(ctx context.Context) ([]ShippingZone, error) {
	rows, err := q.db.Query(ctx, listShippingZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShippingZone{}
	for rows.Next() {
		var i ShippingZone
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.IsDefault,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShippingMethod = `-- name: UpdateShippingMethod :one
UPDATE "ShippingMethod"
SET "code" = $2, "isPickup" = $3, "enabled" = $4,
    "estimatedDaysMin" = $5, "estimatedDaysMax" = $6, "updatedAt" = NOW()
WHERE "id" = $1
RETURNING id, code, "isPickup", enabled, "estimatedDaysMin", "estimatedDaysMax", "createdAt", "updatedAt"
`

type UpdateShippingMethodParams struct {
	ID               string `json:"id"`
	Code             string `json:"code"`
	IsPickup         bool   `json:"isPickup"`
	Enabled          bool   `json:"enabled"`
	EstimatedDaysMin *int32 `json:"estimatedDaysMin"`
	EstimatedDaysMax *int32 `json:"estimatedDaysMax"`
}

func (q *Queries) UpdateShippingMethod(ctx context.Context, arg UpdateShippingMethodParams) (ShippingMethod, error) {
	row := q.db.QueryRow(ctx, updateShippingMethod,
		arg.ID,
		arg.Code,
		arg.IsPickup,
		arg.Enabled,
		arg.EstimatedDaysMin,
		arg.EstimatedDaysMax,
	)
	var i ShippingMethod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.IsPickup,
		&i.Enabled,
		&i.EstimatedDaysMin,
		&i.EstimatedDaysMax,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShippingZone = `-- name: UpdateShippingZone :one
UPDATE "ShippingZone"
SET "code" = $2, "isDefault" = $3, "priority" = $4, "updatedAt" = NOW()
WHERE "id" = $1
RETURNING id, code, "isDefault", priority, "createdAt", "updatedAt"
`

type UpdateShippingZoneParams struct {
	ID        string `json:"id"`
	Code      string `json:"code"`
	IsDefault bool   `json:"isDefault"`
	Priority  int32  `json:"priority"`
}

func (q *Queries) UpdateShippingZone(ctx context.Context, arg UpdateShippingZoneParams) (ShippingZone, error) {
	row := q.db.QueryRow(ctx, updateShippingZone,
		arg.ID,
		arg.Code,
		arg.IsDefault,
		arg.Priority,
	)
	var i ShippingZone
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.IsDefault,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertShippingMethodTranslation = `-- name: UpsertShippingMethodTranslation :one
INSERT INTO "ShippingMethodTranslation" ("id", "methodId", "locale", "name", "description")
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ("methodId", "locale") DO UPDATE SET "name" = EXCLUDED."name", "description" = EXCLUDED."description"
RETURNING id, "methodId", locale, name, description
`

type UpsertShippingMethodTranslationParams struct {
	ID          string  `json:"id"`
	MethodId    string  `json:"methodId"`
	Locale      Locale  `json:"locale"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) UpsertShippingMethodTranslation(ctx context.Context, arg UpsertShippingMethodTranslationParams) (ShippingMethodTranslation, error) {
	row := q.db.QueryRow(ctx, upsertShippingMethodTranslation,
		arg.ID,
		arg.MethodId,
		arg.Locale,
		arg.Name,
		arg.Description,
	)
	var i ShippingMethodTranslation
	err := row.Scan(
		&i.ID,
		&i.MethodId,
		&i.Locale,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const upsertShippingRate = `-- name: UpsertShippingRate :one
INSERT INTO "ShippingRate" ("id", "zoneId", "methodId", "flatFee", "freeAbove", "currency")
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT ("zoneId", "methodId") DO UPDATE
  SET "flatFee" = EXCLUDED."flatFee", "freeAbove" = EXCLUDED."freeAbove", "currency" = EXCLUDED."currency"
RETURNING id, "zoneId", "methodId", "flatFee", "freeAbove", currency
`

type UpsertShippingRateParams struct {
	ID        string              `json:"id"`
	ZoneId    string              `json:"zoneId"`
	MethodId  string              `json:"methodId"`
	FlatFee   decimal.Decimal     `json:"flatFee"`
	FreeAbove decimal.NullDecimal `json:"freeAbove"`
	Currency  string              `json:"currency"`
}

func (q *Queries) UpsertShippingRate(ctx context.Context, arg UpsertShippingRateParams) (ShippingRate, error) {
	row := q.db.QueryRow(ctx, upsertShippingRate,
		arg.ID,
		arg.ZoneId,
		arg.MethodId,
		arg.FlatFee,
		arg.FreeAbove,
		arg.Currency,
	)
	var i ShippingRate
	err := row.Scan(
		&i.ID,
		&i.ZoneId,
		&i.MethodId,
		&i.FlatFee,
		&i.FreeAbove,
		&i.Currency,
	)
	return i, err
}

const upsertShippingZoneTranslation = `-- name: UpsertShippingZoneTranslation :one
INSERT INTO "ShippingZoneTranslation" ("id", "zoneId", "locale", "name")
VALUES ($1, $2, $3, $4)
ON CONFLICT ("zoneId", "locale") DO UPDATE SET "name" = EXCLUDED."name"
RETURNING id, "zoneId", locale, name
`

type UpsertShippingZoneTranslationParams struct {
	ID     string `json:"id"`
	ZoneId string `json:"zoneId"`
	Locale Locale `json:"locale"`
	Name   string `json:"name"`
}

func (q *Queries) UpsertShippingZoneTranslation(ctx context.Context, arg UpsertShippingZoneTranslationParams) (ShippingZoneTranslation, error) {
	row := q.db.QueryRow(ctx, upsertShippingZoneTranslation,
		arg.ID,
		arg.ZoneId,
		arg.Locale,
		arg.Name,
	)
	var i ShippingZoneTranslation
	err := row.Scan(
		&i.ID,
		&i.ZoneId,
		&i.Locale,
		&i.Name,
	)
	return i, err
}
