// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTag = `-- name: CreateTag :one
INSERT INTO "Tag" ("id", "slug", "createdAt")
VALUES ($1, $2, NOW())
RETURNING id, slug, "wpId", "createdAt"
`

type CreateTagParams struct {
	ID   string `json:"id"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.ID, arg.Slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.WpId,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM "Tag" WHERE "id" = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, slug, "wpId", "createdAt" FROM "Tag" WHERE "id" = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.WpId,
		&i.CreatedAt,
	)
	return i, err
}

const getTagBySlug = `-- name: GetTagBySlug :one
SELECT id, slug, "wpId", "createdAt" FROM "Tag" WHERE "slug" = $1
`

func (q *Queries) GetTagBySlug(ctx context.Context, slug string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagBySlug, slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.WpId,
		&i.CreatedAt,
	)
	return i, err
}

const getTagTranslations = `-- name: GetTagTranslations :many
SELECT id, "tagId", locale, name FROM "TagTranslation" WHERE "tagId" = $1 AND "locale" = $2
`

type GetTagTranslationsParams struct {
	TagId  string `json:"tagId"`
	Locale Locale `json:"locale"`
}

func (q *Queries) GetTagTranslations(ctx context.Context, arg GetTagTranslationsParams) ([]TagTranslation, error) {
	rows, err := q.db.Query(ctx, getTagTranslations, arg.TagId, arg.Locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagTranslation{}
	for rows.Next() {
		var i TagTranslation
		if err := rows.Scan(
			&i.ID,
			&i.TagId,
			&i.Locale,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.slug, t."wpId", t."createdAt", COUNT(*) OVER() AS total_count
FROM "Tag" t
ORDER BY t."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListTagsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListTagsRow struct {
	ID         string           `json:"id"`
	Slug       string           `json:"slug"`
	WpId       *int32           `json:"wpId"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	TotalCount int64            `json:"total_count"`
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.WpId,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE "Tag" SET "slug" = $2 WHERE "id" = $1 RETURNING id, slug, "wpId", "createdAt"
`

type UpdateTagParams struct {
	ID   string `json:"id"`
	Slug string `json:"slug"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.Slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.WpId,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTagTranslation = `-- name: UpsertTagTranslation :one
INSERT INTO "TagTranslation" ("id", "tagId", "locale", "name")
VALUES ($1, $2, $3, $4)
ON CONFLICT ("tagId", "locale") DO UPDATE
  SET "name" = EXCLUDED."name"
RETURNING id, "tagId", locale, name
`

type UpsertTagTranslationParams struct {
	ID     string `json:"id"`
	TagId  string `json:"tagId"`
	Locale Locale `json:"locale"`
	Name   string `json:"name"`
}

func (q *Queries) UpsertTagTranslation(ctx context.Context, arg UpsertTagTranslationParams) (TagTranslation, error) {
	row := q.db.QueryRow(ctx, upsertTagTranslation,
		arg.ID,
		arg.TagId,
		arg.Locale,
		arg.Name,
	)
	var i TagTranslation
	err := row.Scan(
		&i.ID,
		&i.TagId,
		&i.Locale,
		&i.Name,
	)
	return i, err
}
