// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO "Address" ("id", "userId", "label", "firstName", "lastName", "company", "line1", "line2", "city", "postalCode", "country", "isDefault")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, "userId", label, "firstName", "lastName", company, line1, line2, city, "postalCode", country, "isDefault"
`

type CreateAddressParams struct {
	ID         string  `json:"id"`
	UserId     string  `json:"userId"`
	Label      *string `json:"label"`
	FirstName  string  `json:"firstName"`
	LastName   string  `json:"lastName"`
	Company    *string `json:"company"`
	Line1      string  `json:"line1"`
	Line2      *string `json:"line2"`
	City       string  `json:"city"`
	PostalCode string  `json:"postalCode"`
	Country    string  `json:"country"`
	IsDefault  bool    `json:"isDefault"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.ID,
		arg.UserId,
		arg.Label,
		arg.FirstName,
		arg.LastName,
		arg.Company,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.PostalCode,
		arg.Country,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Label,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.PostalCode,
		&i.Country,
		&i.IsDefault,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM "Address" WHERE "id" = $1
`

func (q *Queries) DeleteAddress(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAddress, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "User" WHERE "id" = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, "userId", label, "firstName", "lastName", company, line1, line2, city, "postalCode", country, "isDefault" FROM "Address" WHERE "id" = $1
`

func (q *Queries) GetAddressByID(ctx context.Context, id string) (Address, error) {
	row := q.db.QueryRow(ctx, getAddressByID, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Label,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.PostalCode,
		&i.Country,
		&i.IsDefault,
	)
	return i, err
}

const getUserAddresses = `-- name: GetUserAddresses :many
SELECT id, "userId", label, "firstName", "lastName", company, line1, line2, city, "postalCode", country, "isDefault" FROM "Address"
WHERE "userId" = $1
ORDER BY "isDefault" DESC, "id" ASC
`

func (q *Queries) GetUserAddresses(ctx context.Context, userid string) ([]Address, error) {
	rows, err := q.db.Query(ctx, getUserAddresses, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.Label,
			&i.FirstName,
			&i.LastName,
			&i.Company,
			&i.Line1,
			&i.Line2,
			&i.City,
			&i.PostalCode,
			&i.Country,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByIDFull = `-- name: GetUserByIDFull :one
SELECT "id", "email", "firstName", "lastName", "role", "preferredLocale", "phone", "createdAt"
FROM "User" WHERE "id" = $1
`

type GetUserByIDFullRow struct {
	ID              string           `json:"id"`
	Email           string           `json:"email"`
	FirstName       *string          `json:"firstName"`
	LastName        *string          `json:"lastName"`
	Role            UserRole         `json:"role"`
	PreferredLocale Locale           `json:"preferredLocale"`
	Phone           *string          `json:"phone"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) GetUserByIDFull(ctx context.Context, id string) (GetUserByIDFullRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDFull, id)
	var i GetUserByIDFullRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.PreferredLocale,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT "id", "email", "firstName", "lastName", "role", "preferredLocale", "phone", "createdAt",
       COUNT(*) OVER() AS total_count
FROM "User"
WHERE ($3::text IS NULL OR
       "email" ILIKE '%' || $3::text || '%' OR
       "firstName" ILIKE '%' || $3::text || '%' OR
       "lastName" ILIKE '%' || $3::text || '%')
ORDER BY "createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Search *string `json:"search"`
}

type ListUsersRow struct {
	ID              string           `json:"id"`
	Email           string           `json:"email"`
	FirstName       *string          `json:"firstName"`
	LastName        *string          `json:"lastName"`
	Role            UserRole         `json:"role"`
	PreferredLocale Locale           `json:"preferredLocale"`
	Phone           *string          `json:"phone"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	TotalCount      int64            `json:"total_count"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.PreferredLocale,
			&i.Phone,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsetDefaultAddresses = `-- name: UnsetDefaultAddresses :exec
UPDATE "Address" SET "isDefault" = false WHERE "userId" = $1
`

func (q *Queries) UnsetDefaultAddresses(ctx context.Context, userid string) error {
	_, err := q.db.Exec(ctx, unsetDefaultAddresses, userid)
	return err
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE "Address"
SET "label" = $2,
    "firstName" = COALESCE($3, "firstName"),
    "lastName" = COALESCE($4, "lastName"),
    "company" = $5,
    "line1" = COALESCE($6, "line1"),
    "line2" = $7,
    "city" = COALESCE($8, "city"),
    "postalCode" = COALESCE($9, "postalCode"),
    "country" = COALESCE($10, "country"),
    "isDefault" = COALESCE($11::bool, "isDefault")
WHERE "id" = $1
RETURNING id, "userId", label, "firstName", "lastName", company, line1, line2, city, "postalCode", country, "isDefault"
`

type UpdateAddressParams struct {
	ID         string  `json:"id"`
	Label      *string `json:"label"`
	FirstName  *string `json:"first_name"`
	LastName   *string `json:"last_name"`
	Company    *string `json:"company"`
	Line1      *string `json:"line1"`
	Line2      *string `json:"line2"`
	City       *string `json:"city"`
	PostalCode *string `json:"postal_code"`
	Country    *string `json:"country"`
	IsDefault  *bool   `json:"is_default"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.ID,
		arg.Label,
		arg.FirstName,
		arg.LastName,
		arg.Company,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.PostalCode,
		arg.Country,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Label,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.PostalCode,
		&i.Country,
		&i.IsDefault,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE "User"
SET "firstName" = COALESCE($2, "firstName"),
    "lastName" = COALESCE($3, "lastName"),
    "phone" = COALESCE($4, "phone"),
    "role" = COALESCE($5::"UserRole", "role"),
    "preferredLocale" = COALESCE($6::"Locale", "preferredLocale"),
    "updatedAt" = NOW()
WHERE "id" = $1
RETURNING "id", "email", "firstName", "lastName", "role", "preferredLocale", "phone", "createdAt"
`

type UpdateUserParams struct {
	ID              string    `json:"id"`
	FirstName       *string   `json:"first_name"`
	LastName        *string   `json:"last_name"`
	Phone           *string   `json:"phone"`
	Role            *UserRole `json:"role"`
	PreferredLocale *Locale   `json:"preferred_locale"`
}

type UpdateUserRow struct {
	ID              string           `json:"id"`
	Email           string           `json:"email"`
	FirstName       *string          `json:"firstName"`
	LastName        *string          `json:"lastName"`
	Role            UserRole         `json:"role"`
	PreferredLocale Locale           `json:"preferredLocale"`
	Phone           *string          `json:"phone"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Role,
		arg.PreferredLocale,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.PreferredLocale,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}
